// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/mathlib_extended/FuseVariableIndex_t.hpp>
#include <SDK/mathlib_extended/FuseVariableType_t.hpp>
#include <SDK/mathlib_extended/FuseVariableAccess_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace mathlib_extended {
		class VariableInfo_t  {
		public:
			PROPERTY(m_name,GlobalTypes::CUtlString*, 0x0);
			PROPERTY(m_nameToken,GlobalTypes::CUtlStringToken*, 0x8);
			NESTED_PROPERTY(m_nIndex,mathlib_extended::FuseVariableIndex_t, 0xc);
			PROPERTY(m_nNumComponents,uint8_t, 0xe);
			PROPERTY(m_eVarType,mathlib_extended::FuseVariableType_t, 0xf);
			PROPERTY(m_eAccess,mathlib_extended::FuseVariableAccess_t, 0x10);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::mathlib_extended::VariableInfo_t) == 0x18, "VariableInfo_t size should be 0x18");
	}
}
