// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x970
			namespace CBaseProp /*: public CS2::server::CBaseAnimGraph*/ {
				constexpr std::ptrdiff_t m_bModelOverrodeBlockLOS = 0x940; // bool m_bModelOverrodeBlockLOS; |  0x940 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_iShapeType = 0x944; // int32_t m_iShapeType; |  0x944 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bConformToCollisionBounds = 0x948; // bool m_bConformToCollisionBounds; |  0x948 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_mPreferredCatchTransform = 0x950; // GlobalTypes::CTransform  | Schema_Atomic | Size: 0x20
			}
		}
	}
}
