// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x8A0
			namespace CEnvBeam /*: public CS2::server::CBeam*/ {
				constexpr std::ptrdiff_t m_active = 0x808; // int32_t m_active; |  0x808 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_spriteTexture = 0x810; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszStartEntity = 0x818; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszEndEntity = 0x820; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_life = 0x828; // float32 m_life; |  0x828 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_boltWidth = 0x82c; // float32 m_boltWidth; |  0x82c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_noiseAmplitude = 0x830; // float32 m_noiseAmplitude; |  0x830 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_speed = 0x834; // int32_t m_speed; |  0x834 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_restrike = 0x838; // float32 m_restrike; |  0x838 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_iszSpriteName = 0x840; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_frameStart = 0x848; // int32_t m_frameStart; |  0x848 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_vEndPointWorld = 0x84c; // GlobalTypes::VectorWS  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vEndPointRelative = 0x858; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_radius = 0x864; // float32 m_radius; |  0x864 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_TouchType = 0x868; // server::Touch_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_iFilterName = 0x870; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hFilter = 0x878; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_iszDecal = 0x880; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_OnTouchedByEntity = 0x888; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
			}
		}
	}
}
