// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xA20
			namespace CFuncMover /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_iszPathName = 0x768; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hPathMover = 0x770; // GlobalTypes::CHandle<server::CPathMover>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_hPrevPathMover = 0x774; // GlobalTypes::CHandle<server::CPathMover>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_iszPathNodeStart = 0x778; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszPathNodeEnd = 0x780; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_bIgnoreEndNode = 0x788; // bool m_bIgnoreEndNode; |  0x788 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_eMoveType = 0x78c; // server::CFuncMover::Move_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bIsReversing = 0x790; // bool m_bIsReversing; |  0x790 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flStartSpeed = 0x794; // float32 m_flStartSpeed; |  0x794 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flPathLocation = 0x798; // float32 m_flPathLocation; |  0x798 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flT = 0x79c; // float32 m_flT; |  0x79c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nCurrentNodeIndex = 0x7a0; // int32_t m_nCurrentNodeIndex; |  0x7a0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nPreviousNodeIndex = 0x7a4; // int32_t m_nPreviousNodeIndex; |  0x7a4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_eSolidType = 0x7a8; // client::SolidType_t  | Schema_DeclaredEnum | Size: 0x1
				constexpr std::ptrdiff_t m_bIsMoving = 0x7a9; // bool m_bIsMoving; |  0x7a9 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flTimeToReachMaxSpeed = 0x7ac; // float32 m_flTimeToReachMaxSpeed; |  0x7ac | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flDistanceToReachMaxSpeed = 0x7b0; // float32 m_flDistanceToReachMaxSpeed; |  0x7b0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeToReachZeroSpeed = 0x7b4; // float32 m_flTimeToReachZeroSpeed; |  0x7b4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flComputedDistanceToReachMaxSpeed = 0x7b8; // float32 m_flComputedDistanceToReachMaxSpeed; |  0x7b8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flComputedDistanceToReachZeroSpeed = 0x7bc; // float32 m_flComputedDistanceToReachZeroSpeed; |  0x7bc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flStartCurveScale = 0x7c0; // float32 m_flStartCurveScale; |  0x7c0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flStopCurveScale = 0x7c4; // float32 m_flStopCurveScale; |  0x7c4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flDistanceToReachZeroSpeed = 0x7c8; // float32 m_flDistanceToReachZeroSpeed; |  0x7c8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeMovementStart = 0x7cc; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeMovementStop = 0x7d0; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_hStopAtNode = 0x7d4; // GlobalTypes::CHandle<server::CMoverPathNode>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_flPathLocationToBeginStop = 0x7d8; // float32 m_flPathLocationToBeginStop; |  0x7d8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flPathLocationStart = 0x7dc; // float32 m_flPathLocationStart; |  0x7dc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flBeginStopT = 0x7e0; // float32 m_flBeginStopT; |  0x7e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_iszStartForwardSound = 0x7e8; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszLoopForwardSound = 0x7f0; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszStopForwardSound = 0x7f8; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszStartReverseSound = 0x800; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszLoopReverseSound = 0x808; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszStopReverseSound = 0x810; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszArriveAtDestinationSound = 0x818; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_OnMovementEnd = 0x838; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bStartAtClosestPoint = 0x850; // bool m_bStartAtClosestPoint; |  0x850 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bStartAtEnd = 0x851; // bool m_bStartAtEnd; |  0x851 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bStartFollowingClosestMover = 0x852; // bool m_bStartFollowingClosestMover; |  0x852 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_eOrientationUpdate = 0x854; // server::CFuncMover::OrientationUpdate_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeStartOrientationChange = 0x858; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeToBlendToNewOrientation = 0x85c; // float32 m_flTimeToBlendToNewOrientation; |  0x85c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flDurationBlendToNewOrientationRan = 0x860; // float32 m_flDurationBlendToNewOrientationRan; |  0x860 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bCreateMovableNavMesh = 0x864; // bool m_bCreateMovableNavMesh; |  0x864 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bAllowMovableNavMeshDockingOnEntireEntity = 0x865; // bool m_bAllowMovableNavMeshDockingOnEntireEntity; |  0x865 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_OnNodePassed = 0x868; // GlobalTypes::CEntityOutputTemplate<GlobalTypes::CUtlString>  | Schema_Atomic | Size: 0x20
				constexpr std::ptrdiff_t m_iszOrientationMatchEntityName = 0x888; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hOrientationMatchEntity = 0x890; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeToTraverseToNextNode = 0x894; // float32 m_flTimeToTraverseToNextNode; |  0x894 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_vLerpToNewPosStartInPathEntitySpace = 0x898; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vLerpToNewPosEndInPathEntitySpace = 0x8a4; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flLerpToPositionT = 0x8b0; // float32 m_flLerpToPositionT; |  0x8b0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flLerpToPositionDeltaT = 0x8b4; // float32 m_flLerpToPositionDeltaT; |  0x8b4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_OnLerpToPositionComplete = 0x8b8; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bIsPaused = 0x8d0; // bool m_bIsPaused; |  0x8d0 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_eTransitionedToPathNodeAction = 0x8d4; // server::CFuncMover::TransitionToPathNodeAction_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_qTransitionSourceOrientation = 0x8e0; // GlobalTypes::Quaternion  | Schema_Atomic | Size: 0x10
				constexpr std::ptrdiff_t m_nDelayedTeleportToNode = 0x8f0; // int32_t m_nDelayedTeleportToNode; |  0x8f0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bIsImGuiLogging = 0x8f4; // bool m_bIsImGuiLogging; |  0x8f4 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_hFollowEntity = 0x8f8; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowDistance = 0x8fc; // float32 m_flFollowDistance; |  0x8fc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMinimumSpeed = 0x900; // float32 m_flFollowMinimumSpeed; |  0x900 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flCurFollowEntityT = 0x904; // float32 m_flCurFollowEntityT; |  0x904 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flCurFollowSpeed = 0x908; // float32 m_flCurFollowSpeed; |  0x908 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_strOrientationFaceEntityName = 0x910; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hOrientationFaceEntity = 0x918; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_OnStart = 0x920; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_OnStartForward = 0x938; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_OnStartReverse = 0x950; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_OnStop = 0x968; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_OnStopped = 0x980; // entity2::CEntityIOOutput  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bNextNodeReturnsCurrent = 0x998; // bool m_bNextNodeReturnsCurrent; |  0x998 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bStartedMoving = 0x999; // bool m_bStartedMoving; |  0x999 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_eFollowEntityDirection = 0x9b8; // server::CFuncMover::FollowEntityDirection_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_hFollowMover = 0x9bc; // GlobalTypes::CHandle<server::CFuncMover>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_iszFollowMoverEntityName = 0x9c0; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_flFollowMoverDistance = 0x9c8; // float32 m_flFollowMoverDistance; |  0x9c8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMoverRatio = 0x9cc; // float32 m_flFollowMoverRatio; |  0x9cc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMoverCalculatedDistance = 0x9d0; // float32 m_flFollowMoverCalculatedDistance; |  0x9d0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMoverSpringStrength = 0x9d4; // float32 m_flFollowMoverSpringStrength; |  0x9d4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nFollowMoverConstraintPriority = 0x9d8; // int32_t m_nFollowMoverConstraintPriority; |  0x9d8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bFollowConstraintsInitialized = 0x9dc; // bool m_bFollowConstraintsInitialized; |  0x9dc | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_eFollowConstraint = 0x9e0; // server::CFuncMover::FollowConstraint_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMoverSpeed = 0x9e4; // float32 m_flFollowMoverSpeed; |  0x9e4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFollowMoverVelocity = 0x9e8; // float32 m_flFollowMoverVelocity; |  0x9e8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nTickMovementRan = 0x9ec; // entity2::GameTick_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_movementSummary = 0x9f0; // server::FuncMoverMovementSummary_t  | Schema_DeclaredClass | Size: 0x20
				constexpr std::ptrdiff_t m_bStopFromBeginStopTarget = 0xa10; // bool m_bStopFromBeginStopTarget; |  0xa10 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bQueueStop = 0xa11; // bool m_bQueueStop; |  0xa11 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bQueueStopMoving = 0xa12; // bool m_bQueueStopMoving; |  0xa12 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
