// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x770
			namespace CFuncWall /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_nState = 0x768; // int32_t m_nState; |  0x768 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
