// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xA00
			namespace CItemDefuser /*: public CS2::server::CItem*/ {
				constexpr std::ptrdiff_t m_entitySpottedState = 0x9e0; // server::EntitySpottedState_t  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_nSpotRules = 0x9f8; // int32_t m_nSpotRules; |  0x9f8 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
