// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x7A0
			namespace CTextureBasedAnimatable /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_bLoop = 0x768; // bool m_bLoop; |  0x768 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flFPS = 0x76c; // float32 m_flFPS; |  0x76c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hPositionKeys = 0x770; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hRotationKeys = 0x778; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_vAnimationBoundsMin = 0x780; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vAnimationBoundsMax = 0x78c; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flStartTime = 0x798; // float32 m_flStartTime; |  0x798 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flStartFrame = 0x79c; // float32 m_flStartFrame; |  0x79c | Schema_Builtin | Size: 0x4
			}
		}
	}
}
