// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseCell_BaseYieldingInflow.hpp>
#include <SDK/pulse_runtime_lib/SignatureOutflow_Continue.hpp>
#include <SDK/pulse_runtime_lib/SignatureOutflow_Resume.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_system {
		class CPulseCell_Test_MultiOutflow_WithParams_Yielding : public CS2::pulse_runtime_lib::CPulseCell_BaseYieldingInflow {
		public:
			NESTED_PROPERTY(m_Out1,pulse_runtime_lib::SignatureOutflow_Continue, 0x48);
			NESTED_PROPERTY(m_AsyncChild1,pulse_runtime_lib::SignatureOutflow_Continue, 0x90);
			NESTED_PROPERTY(m_AsyncChild2,pulse_runtime_lib::SignatureOutflow_Continue, 0xd8);
			NESTED_PROPERTY(m_YieldResume1,pulse_runtime_lib::SignatureOutflow_Resume, 0x120);
			NESTED_PROPERTY(m_YieldResume2,pulse_runtime_lib::SignatureOutflow_Resume, 0x168);
			S2_PAD(0x168);
		};
		//static_assert(sizeof(CS2::pulse_system::CPulseCell_Test_MultiOutflow_WithParams_Yielding) == 0x1B0, "CPulseCell_Test_MultiOutflow_WithParams_Yielding size should be 0x1B0");
	}
}
