// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_system {
		class TestComponent_t  {
		public:
			PROPERTY(m_ComponentData,GlobalTypes::CUtlString*, 0x8);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::pulse_system::TestComponent_t) == 0x10, "TestComponent_t size should be 0x10");

#endif
	}
}
