// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/PulseGraphInstanceID_t.hpp>



namespace CS2 {
	namespace pulse_runtime_lib {
		class PulseGraphExecutionHistoryEntry_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class CPulseGraphExecutionHistory  {
		public:
			NESTED_PROPERTY(m_nInstanceID,pulse_runtime_lib::PulseGraphInstanceID_t, 0x0);
			PROPERTY(m_strFileName,GlobalTypes::CUtlString*, 0x8);
			NESTED_PROPERTY(m_vecHistory,GlobalTypes::CUtlVector<pulse_runtime_lib::PulseGraphExecutionHistoryEntry_t*>, 0x10);
			PROPERTY(m_mapCellDesc,GlobalTypes::CUtlOrderedMap< PulseDocNodeID_t, PulseGraphExecutionHistoryNodeDesc_t >, 0x28);
			PROPERTY(m_mapCursorDesc,GlobalTypes::CUtlOrderedMap< PulseCursorID_t, PulseGraphExecutionHistoryCursorDesc_t >, 0x50);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::pulse_runtime_lib::CPulseGraphExecutionHistory) == 0x78, "CPulseGraphExecutionHistory size should be 0x78");
	}
}
