// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseCell_BaseFlow.hpp>
#include <SDK/pulse_runtime_lib/PulseRuntimeChunkIndex_t.hpp>
#include <SDK/pulse_runtime_lib/PulseRegisterMap_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class CPulseCell_Inflow_BaseEntrypoint : public CS2::pulse_runtime_lib::CPulseCell_BaseFlow {
		public:
			NESTED_PROPERTY(m_EntryChunk,pulse_runtime_lib::PulseRuntimeChunkIndex_t, 0x48);
			NESTED_PROPERTY(m_RegisterMap,pulse_runtime_lib::PulseRegisterMap_t, 0x50);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::pulse_runtime_lib::CPulseCell_Inflow_BaseEntrypoint) == 0x80, "CPulseCell_Inflow_BaseEntrypoint size should be 0x80");
	}
}
