// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseCell_BaseYieldingInflow.hpp>
#include <SDK/pulse_runtime_lib/PulseObservableBoolExpression_t.hpp>
#include <SDK/pulse_runtime_lib/CPulse_ResumePoint.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class CPulseCell_WaitForObservable : public CS2::pulse_runtime_lib::CPulseCell_BaseYieldingInflow {
		public:
			NESTED_PROPERTY(m_Condition,pulse_runtime_lib::PulseObservableBoolExpression_t, 0x48);
			NESTED_PROPERTY(m_OnTrue,pulse_runtime_lib::CPulse_ResumePoint, 0xc0);
			S2_PAD(0xC0);
		};
		//static_assert(sizeof(CS2::pulse_runtime_lib::CPulseCell_WaitForObservable) == 0x108, "CPulseCell_WaitForObservable size should be 0x108");
	}
}
