// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/OutflowWithRequirements_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class PulseSelectorOutflowList_t  {
		public:
			NESTED_PROPERTY(m_Outflows,IDENTITY(GlobalTypes::CUtlVector<pulse_runtime_lib::OutflowWithRequirements_t>), 0x0);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::pulse_runtime_lib::PulseSelectorOutflowList_t) == 0x18, "PulseSelectorOutflowList_t size should be 0x18");

#endif
	}
}
