// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/PulseCursorID_t.hpp>
#include <SDK/pulse_runtime_lib/PulseDocNodeID_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class PulseGraphExecutionHistoryCursorDesc_t  {
		public:
			NESTED_PROPERTY(vecAncestorCursorIDs,GlobalTypes::CUtlVector<pulse_runtime_lib::PulseCursorID_t>, 0x0);
			NESTED_PROPERTY(nSpawnNodeID,pulse_runtime_lib::PulseDocNodeID_t, 0x18);
			NESTED_PROPERTY(nRetiredAtNodeID,pulse_runtime_lib::PulseDocNodeID_t, 0x1c);
			PROPERTY(flLastReferenced,float32, 0x20);
			PROPERTY(nLastValidEntryIdx,int32_t, 0x24);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::pulse_runtime_lib::PulseGraphExecutionHistoryCursorDesc_t) == 0x28, "PulseGraphExecutionHistoryCursorDesc_t size should be 0x28");
	}
}
