// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace worldrenderer {
		class AggregateVertexAlbedoStreamOnDiskData_t  {
		public:
			PROPERTY(m_BufferData,GlobalTypes::CUtlBinaryBlock, 0x0);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::worldrenderer::AggregateVertexAlbedoStreamOnDiskData_t) == 0x10, "AggregateVertexAlbedoStreamOnDiskData_t size should be 0x10");
	}
}
