// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/CVMixBaseProcessorDesc.hpp>
#include <SDK/soundsystem_lowlevel/VMixSubgraphSwitchDesc_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class CVMixSubgraphSwitchProcessorDesc : public CS2::soundsystem_lowlevel::CVMixBaseProcessorDesc {
		public:
			NESTED_PROPERTY(m_desc,IDENTITY(soundsystem_lowlevel::VMixSubgraphSwitchDesc_t), 0x20);
			S2_PAD(0x38);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::soundsystem_lowlevel::CVMixSubgraphSwitchProcessorDesc) == 0x58, "CVMixSubgraphSwitchProcessorDesc size should be 0x58");

#endif
	}
}
