// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/CVMixBaseProcessorDesc.hpp>
#include <SDK/soundsystem_lowlevel/VMixDualCompressorDesc_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class CVMixDualCompressorProcessorDesc : public CS2::soundsystem_lowlevel::CVMixBaseProcessorDesc {
		public:
			NESTED_PROPERTY(m_desc,soundsystem_lowlevel::VMixDualCompressorDesc_t, 0x20);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::CVMixDualCompressorProcessorDesc) == 0x58, "CVMixDualCompressorProcessorDesc size should be 0x58");
	}
}
