// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/VMixDynamicsBand_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class VMixDynamics3BandDesc_t  {
		public:
			PROPERTY(m_fldbGainOutput,float32, 0x0);
			PROPERTY(m_flRMSTimeMS,float32, 0x4);
			PROPERTY(m_fldbKneeWidth,float32, 0x8);
			PROPERTY(m_flDepth,float32, 0xc);
			PROPERTY(m_flWetMix,float32, 0x10);
			PROPERTY(m_flTimeScale,float32, 0x14);
			PROPERTY(m_flLowCutoffFreq,float32, 0x18);
			PROPERTY(m_flHighCutoffFreq,float32, 0x1c);
			PROPERTY(m_bPeakMode,bool, 0x20);
			PROPERTY_ARRAY(m_bandDesc,soundsystem_lowlevel::VMixDynamicsBand_t, 3 , 0x24);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::VMixDynamics3BandDesc_t) == 0x90, "VMixDynamics3BandDesc_t size should be 0x90");
	}
}
