// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class VMixPitchShiftDesc_t  {
		public:
			PROPERTY(m_nGrainSampleCount,int32_t, 0x0);
			PROPERTY(m_flPitchShift,float32, 0x4);
			PROPERTY(m_nQuality,int32_t, 0x8);
			PROPERTY(m_nProcType,int32_t, 0xc);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::VMixPitchShiftDesc_t) == 0x10, "VMixPitchShiftDesc_t size should be 0x10");
	}
}
