// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/VMixFilterDesc_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class VMixModDelayDesc_t  {
		public:
			NESTED_PROPERTY(m_feedbackFilter,soundsystem_lowlevel::VMixFilterDesc_t, 0x0);
			PROPERTY(m_bPhaseInvert,bool, 0x10);
			PROPERTY(m_flGlideTime,float32, 0x14);
			PROPERTY(m_flDelay,float32, 0x18);
			PROPERTY(m_flOutputGain,float32, 0x1c);
			PROPERTY(m_flFeedbackGain,float32, 0x20);
			PROPERTY(m_flModRate,float32, 0x24);
			PROPERTY(m_flModDepth,float32, 0x28);
			PROPERTY(m_bApplyAntialiasing,bool, 0x2c);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::VMixModDelayDesc_t) == 0x30, "VMixModDelayDesc_t size should be 0x30");
	}
}
