// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/VMixFilterDesc_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class VMixEQ8Desc_t  {
		public:
			PROPERTY_ARRAY(m_stages,soundsystem_lowlevel::VMixFilterDesc_t, 8 , 0x0);
			S2_PAD(0x80);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::VMixEQ8Desc_t) == 0x80, "VMixEQ8Desc_t size should be 0x80");
	}
}
