// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x360
			namespace C_INIT_CreateFromCPs /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_nIncrement = 0x1e0; // int32_t m_nIncrement; |  0x1e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nMinCP = 0x1e4; // int32_t m_nMinCP; |  0x1e4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nMaxCP = 0x1e8; // int32_t m_nMaxCP; |  0x1e8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nDynamicCPCount = 0x1f0; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
			}
		}
	}
}
