// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x210
			namespace C_INIT_RemapParticleCountToScalar /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_nFieldOutput = 0x1e0; // particles::ParticleAttributeIndex_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_nInputMin = 0x1e4; // int32_t m_nInputMin; |  0x1e4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nInputMax = 0x1e8; // int32_t m_nInputMax; |  0x1e8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nScaleControlPoint = 0x1ec; // int32_t m_nScaleControlPoint; |  0x1ec | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nScaleControlPointField = 0x1f0; // int32_t m_nScaleControlPointField; |  0x1f0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flOutputMin = 0x1f4; // float32 m_flOutputMin; |  0x1f4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flOutputMax = 0x1f8; // float32 m_flOutputMax; |  0x1f8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nSetMethod = 0x1fc; // particleslib::ParticleSetMethod_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bActiveRange = 0x200; // bool m_bActiveRange; |  0x200 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bInvert = 0x201; // bool m_bInvert; |  0x201 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bWrap = 0x202; // bool m_bWrap; |  0x202 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flRemapBias = 0x204; // float32 m_flRemapBias; |  0x204 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
