// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1F0
			namespace C_INIT_PositionOffsetToCP /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_nControlPointNumberStart = 0x1e0; // int32_t m_nControlPointNumberStart; |  0x1e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nControlPointNumberEnd = 0x1e4; // int32_t m_nControlPointNumberEnd; |  0x1e4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bLocalCoords = 0x1e8; // bool m_bLocalCoords; |  0x1e8 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
