// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0xC30
			namespace C_INIT_PositionPlaceOnGround /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_flOffset = 0x1e0; // particleslib::CPerParticleFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flMaxTraceLength = 0x350; // particleslib::CPerParticleFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_vecTraceDir = 0x4c0; // particleslib::CPerParticleVecInput  | Schema_DeclaredClass | Size: 0x6b8
				constexpr std::ptrdiff_t m_CollisionGroupName = 0xb78; // char m_CollisionGroupName[128]; |  0xb78 | Schema_FixedArray | Size: 0x80
				constexpr std::ptrdiff_t m_nTraceSet = 0xbf8; // particles::ParticleTraceSet_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_nTraceMissBehavior = 0xc08; // particles::ParticleTraceMissBehavior_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bIncludeWater = 0xc0c; // bool m_bIncludeWater; |  0xc0c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_nAttribute = 0xc10; // particles::ParticleAttributeIndex_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_bSetPXYZOnly = 0xc14; // bool m_bSetPXYZOnly; |  0xc14 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bSetNormal = 0xc15; // bool m_bSetNormal; |  0xc15 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_nGroundNormalAttribute = 0xc18; // particles::ParticleAttributeIndex_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_bOffsetonColOnly = 0xc1c; // bool m_bOffsetonColOnly; |  0xc1c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flOffsetByRadiusFactor = 0xc20; // float32 m_flOffsetByRadiusFactor; |  0xc20 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nPreserveOffsetCP = 0xc24; // int32_t m_nPreserveOffsetCP; |  0xc24 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nIgnoreCP = 0xc28; // int32_t m_nIgnoreCP; |  0xc28 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
