// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1248
			namespace C_INIT_VelocityRandom /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_nControlPointNumber = 0x1e0; // int32_t m_nControlPointNumber; |  0x1e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fSpeedMin = 0x1e8; // particleslib::CPerParticleFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_fSpeedMax = 0x358; // particleslib::CPerParticleFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_LocalCoordinateSystemSpeedMin = 0x4c8; // particleslib::CPerParticleVecInput  | Schema_DeclaredClass | Size: 0x6b8
				constexpr std::ptrdiff_t m_LocalCoordinateSystemSpeedMax = 0xb80; // particleslib::CPerParticleVecInput  | Schema_DeclaredClass | Size: 0x6b8
				constexpr std::ptrdiff_t m_bIgnoreDT = 0x1238; // bool m_bIgnoreDT; |  0x1238 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_randomnessParameters = 0x123c; // particles::CRandomNumberGeneratorParameters  | Schema_DeclaredClass | Size: 0x8
			}
		}
	}
}
