// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x640
			namespace C_OP_RepeatedTriggerChildGroup /*: public CS2::particles::CParticleFunctionPreEmission*/ {
				constexpr std::ptrdiff_t m_nChildGroupID = 0x1e0; // int32_t m_nChildGroupID; |  0x1e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flClusterRefireTime = 0x1e8; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flClusterSize = 0x358; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flClusterCooldown = 0x4c8; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_bLimitChildCount = 0x638; // bool m_bLimitChildCount; |  0x638 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
