// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x230
			namespace C_OP_RenderScreenVelocityRotate /*: public CS2::particles::CParticleFunctionRenderer*/ {
				constexpr std::ptrdiff_t m_flRotateRateDegrees = 0x228; // float32 m_flRotateRateDegrees; |  0x228 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flForwardDegrees = 0x22c; // float32 m_flForwardDegrees; |  0x22c | Schema_Builtin | Size: 0x4
			}
		}
	}
}
