// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1540
			namespace C_OP_RenderCables /*: public CS2::particles::CParticleFunctionRenderer*/ {
				constexpr std::ptrdiff_t m_flRadiusScale = 0x228; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flAlphaScale = 0x398; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_vecColorScale = 0x508; // particleslib::CParticleCollectionVecInput  | Schema_DeclaredClass | Size: 0x6b8
				constexpr std::ptrdiff_t m_nColorBlendType = 0xbc0; // particleslib::ParticleColorBlendType_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_hMaterial = 0xbc8; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nTextureRepetitionMode = 0xbd0; // particles::TextureRepetitionMode_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flTextureRepeatsPerSegment = 0xbd8; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flTextureRepeatsCircumference = 0xd48; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flColorMapOffsetV = 0xeb8; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flColorMapOffsetU = 0x1028; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flNormalMapOffsetV = 0x1198; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_flNormalMapOffsetU = 0x1308; // particleslib::CParticleCollectionFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_bDrawCableCaps = 0x1478; // bool m_bDrawCableCaps; |  0x1478 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flCapRoundness = 0x147c; // float32 m_flCapRoundness; |  0x147c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flCapOffsetAmount = 0x1480; // float32 m_flCapOffsetAmount; |  0x1480 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flTessScale = 0x1484; // float32 m_flTessScale; |  0x1484 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nMinTesselation = 0x1488; // int32_t m_nMinTesselation; |  0x1488 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nMaxTesselation = 0x148c; // int32_t m_nMaxTesselation; |  0x148c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nRoundness = 0x1490; // int32_t m_nRoundness; |  0x1490 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nForceRoundnessFixed = 0x1494; // bool m_nForceRoundnessFixed; |  0x1494 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_LightingTransform = 0x1498; // particleslib::CParticleTransformInput  | Schema_DeclaredClass | Size: 0x68
				constexpr std::ptrdiff_t m_MaterialFloatVars = 0x1500; // GlobalTypes::CUtlLeanVector<particles::FloatInputMaterialVariable_t>  | Schema_Atomic | Size: 0x10
				constexpr std::ptrdiff_t m_MaterialVecVars = 0x1520; // GlobalTypes::CUtlLeanVector<particles::VecInputMaterialVariable_t>  | Schema_Atomic | Size: 0x10
			}
		}
	}
}
