// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1E8
			namespace C_OP_SetControlPointFromObjectScale /*: public CS2::particles::CParticleFunctionPreEmission*/ {
				constexpr std::ptrdiff_t m_nCPInput = 0x1e0; // int32_t m_nCPInput; |  0x1e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nCPOutput = 0x1e4; // int32_t m_nCPOutput; |  0x1e4 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
