// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0xB78
			namespace C_OP_ScreenSpaceRotateTowardTarget /*: public CS2::particles::CParticleFunctionOperator*/ {
				constexpr std::ptrdiff_t m_vecTargetPosition = 0x1d8; // particleslib::CPerParticleVecInput  | Schema_DeclaredClass | Size: 0x6b8
				constexpr std::ptrdiff_t m_flOutputRemap = 0x890; // particleslib::CParticleRemapFloatInput  | Schema_DeclaredClass | Size: 0x170
				constexpr std::ptrdiff_t m_nSetMethod = 0xa00; // particleslib::ParticleSetMethod_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flScreenEdgeAlignmentDistance = 0xa08; // particleslib::CPerParticleFloatInput  | Schema_DeclaredClass | Size: 0x170
			}
		}
	}
}
