// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1E0
			namespace CParticleFunctionPreEmission /*: public CS2::particles::CParticleFunctionOperator*/ {
				constexpr std::ptrdiff_t m_bRunOnce = 0x1d8; // bool m_bRunOnce; |  0x1d8 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
