// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class CHitBox  {
		public:
			PROPERTY(m_name,GlobalTypes::CUtlString*, 0x0);
			PROPERTY(m_sSurfaceProperty,GlobalTypes::CUtlString*, 0x8);
			PROPERTY(m_sBoneName,GlobalTypes::CUtlString*, 0x10);
			PROPERTY(m_vMinBounds,GlobalTypes::Vector, 0x18);
			PROPERTY(m_vMaxBounds,GlobalTypes::Vector, 0x24);
			PROPERTY(m_flShapeRadius,float32, 0x30);
			PROPERTY(m_nBoneNameHash,uint32_t, 0x34);
			PROPERTY(m_nGroupId,int32_t, 0x38);
			PROPERTY(m_nShapeType,uint8_t, 0x3c);
			PROPERTY(m_bTranslationOnly,bool, 0x3d);
			PROPERTY(m_CRC,uint32_t, 0x40);
			PROPERTY(m_cRenderColor,GlobalTypes::Color, 0x44);
			PROPERTY(m_nHitBoxIndex,uint16_t, 0x48);
			S2_PAD(0x70);
		};
		//static_assert(sizeof(CS2::modellib::CHitBox) == 0x70, "CHitBox size should be 0x70");
	}
}
