// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace modellib {
		class CPhysSurfaceProperties;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class CVPhysXSurfacePropertiesList  {
		public:
			NESTED_PROPERTY(m_surfacePropertiesList,GlobalTypes::CUtlVector<modellib::CPhysSurfaceProperties*>, 0x0);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::modellib::CVPhysXSurfacePropertiesList) == 0x18, "CVPhysXSurfacePropertiesList size should be 0x18");
	}
}
