// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class FrameStamp_t  {
		public:
			PROPERTY(m_flTime,float32, 0x0);
			PROPERTY(m_flEntitySimTime,float32, 0x4);
			PROPERTY(m_bTeleportTick,bool, 0x8);
			PROPERTY(m_bPredicted,bool, 0x9);
			PROPERTY(m_flCurTime,float32, 0xc);
			PROPERTY(m_flRealTime,float32, 0x10);
			PROPERTY(m_nFrameCount,int32_t, 0x14);
			PROPERTY(m_nTickCount,int32_t, 0x18);
			S2_PAD(0x1C);
		};
		//static_assert(sizeof(CS2::modellib::FrameStamp_t) == 0x1C, "SkeletonAnimCapture_t::FrameStamp_t size should be 0x1C");
	}
}
