// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/physicslib/RnSoftbodyParticle_t.hpp>
#include <SDK/physicslib/RnSoftbodySpring_t.hpp>
#include <SDK/physicslib/RnSoftbodyCapsule_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class PhysSoftbodyDesc_t  {
		public:
			NESTED_PROPERTY(m_ParticleBoneHash,GlobalTypes::CUtlVector< uint32 >, 0x0);
			NESTED_PROPERTY(m_Particles,GlobalTypes::CUtlVector<physicslib::RnSoftbodyParticle_t>, 0x18);
			NESTED_PROPERTY(m_Springs,GlobalTypes::CUtlVector<physicslib::RnSoftbodySpring_t>, 0x30);
			NESTED_PROPERTY(m_Capsules,GlobalTypes::CUtlVector<physicslib::RnSoftbodyCapsule_t>, 0x48);
			NESTED_PROPERTY(m_InitPose,GlobalTypes::CUtlVector<GlobalTypes::CTransform>, 0x60);
			PROPERTY(m_ParticleBoneName,GlobalTypes::CUtlVector<GlobalTypes::CUtlString>, 0x78);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::modellib::PhysSoftbodyDesc_t) == 0x90, "PhysSoftbodyDesc_t size should be 0x90");
	}
}
