// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/modellib/VPhysXRange_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class VPhysXJoint_t  {
		public:
			PROPERTY(m_nType,uint16_t, 0x0);
			PROPERTY(m_nBody1,uint16_t, 0x2);
			PROPERTY(m_nBody2,uint16_t, 0x4);
			PROPERTY(m_nFlags,uint16_t, 0x6);
			PROPERTY(m_Frame1,GlobalTypes::CTransform, 0x10);
			PROPERTY(m_Frame2,GlobalTypes::CTransform, 0x30);
			PROPERTY(m_bEnableCollision,bool, 0x50);
			PROPERTY(m_bIsLinearConstraintDisabled,bool, 0x51);
			PROPERTY(m_bIsAngularConstraintDisabled,bool, 0x52);
			PROPERTY(m_bEnableLinearLimit,bool, 0x53);
			NESTED_PROPERTY(m_LinearLimit,modellib::VPhysXRange_t, 0x54);
			PROPERTY(m_bEnableLinearMotor,bool, 0x5c);
			PROPERTY(m_vLinearTargetVelocity,GlobalTypes::Vector, 0x60);
			PROPERTY(m_flMaxForce,float32, 0x6c);
			PROPERTY(m_bEnableSwingLimit,bool, 0x70);
			NESTED_PROPERTY(m_SwingLimit,modellib::VPhysXRange_t, 0x74);
			PROPERTY(m_bEnableTwistLimit,bool, 0x7c);
			NESTED_PROPERTY(m_TwistLimit,modellib::VPhysXRange_t, 0x80);
			PROPERTY(m_bEnableAngularMotor,bool, 0x88);
			PROPERTY(m_vAngularTargetVelocity,GlobalTypes::Vector, 0x8c);
			PROPERTY(m_flMaxTorque,float32, 0x98);
			PROPERTY(m_flLinearFrequency,float32, 0x9c);
			PROPERTY(m_flLinearDampingRatio,float32, 0xa0);
			PROPERTY(m_flAngularFrequency,float32, 0xa4);
			PROPERTY(m_flAngularDampingRatio,float32, 0xa8);
			PROPERTY(m_flFriction,float32, 0xac);
			PROPERTY(m_flElasticity,float32, 0xb0);
			PROPERTY(m_flElasticDamping,float32, 0xb4);
			PROPERTY(m_flPlasticity,float32, 0xb8);
			PROPERTY(m_Tag,GlobalTypes::CUtlString*, 0xc0);
			S2_PAD(0xD0);
		};
		//static_assert(sizeof(CS2::modellib::VPhysXJoint_t) == 0xD0, "VPhysXJoint_t size should be 0xD0");
	}
}
