// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class VsInputSignatureElement_t  {
		public:
			PROPERTY_ARRAY(m_pName,char, 64 , 0x0);
			PROPERTY_ARRAY(m_pSemantic,char, 64 , 0x40);
			PROPERTY_ARRAY(m_pD3DSemanticName,char, 64 , 0x80);
			PROPERTY(m_nD3DSemanticIndex,int32_t, 0xc0);
			S2_PAD(0xC4);
		};
		//static_assert(sizeof(CS2::modellib::VsInputSignatureElement_t) == 0xC4, "VsInputSignatureElement_t size should be 0xC4");
	}
}
