// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_PositionWarp : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_vecWarpMin,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1e0);
			NESTED_PROPERTY(m_vecWarpMax,IDENTITY(particleslib::CParticleCollectionVecInput), 0x898);
			PROPERTY(m_nScaleControlPointNumber,int32_t, 0xf50);
			PROPERTY(m_nControlPointNumber,int32_t, 0xf54);
			PROPERTY(m_nRadiusComponent,int32_t, 0xf58);
			PROPERTY(m_flWarpTime,float32, 0xf5c);
			PROPERTY(m_flWarpStartTime,float32, 0xf60);
			PROPERTY(m_flPrevPosScale,float32, 0xf64);
			PROPERTY(m_bInvertWarp,bool, 0xf68);
			PROPERTY(m_bUseCount,bool, 0xf69);
			S2_PAD(0xD90);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_PositionWarp) == 0xF70, "C_INIT_PositionWarp size should be 0xF70");

#endif
	}
}
