// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateOnGrid : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_nXCount,particleslib::CParticleCollectionFloatInput, 0x1d8);
			NESTED_PROPERTY(m_nYCount,particleslib::CParticleCollectionFloatInput, 0x348);
			NESTED_PROPERTY(m_nZCount,particleslib::CParticleCollectionFloatInput, 0x4b8);
			NESTED_PROPERTY(m_nXSpacing,particleslib::CParticleCollectionFloatInput, 0x628);
			NESTED_PROPERTY(m_nYSpacing,particleslib::CParticleCollectionFloatInput, 0x798);
			NESTED_PROPERTY(m_nZSpacing,particleslib::CParticleCollectionFloatInput, 0x908);
			PROPERTY(m_nControlPointNumber,int32_t, 0xa78);
			PROPERTY(m_bLocalSpace,bool, 0xa7c);
			PROPERTY(m_bCenter,bool, 0xa7d);
			PROPERTY(m_bHollow,bool, 0xa7e);
			S2_PAD(0x8A8);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_CreateOnGrid) == 0xA80, "C_INIT_CreateOnGrid size should be 0xA80");
	}
}
