// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_InitialVelocityNoise : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_vecAbsVal,GlobalTypes::Vector, 0x1e0);
			PROPERTY(m_vecAbsValInv,GlobalTypes::Vector, 0x1ec);
			NESTED_PROPERTY(m_vecOffsetLoc,IDENTITY(particleslib::CPerParticleVecInput), 0x1f8);
			NESTED_PROPERTY(m_flOffset,IDENTITY(particleslib::CPerParticleFloatInput), 0x8b0);
			NESTED_PROPERTY(m_vecOutputMin,IDENTITY(particleslib::CPerParticleVecInput), 0xa20);
			NESTED_PROPERTY(m_vecOutputMax,IDENTITY(particleslib::CPerParticleVecInput), 0x10d8);
			NESTED_PROPERTY(m_flNoiseScale,IDENTITY(particleslib::CPerParticleFloatInput), 0x1790);
			NESTED_PROPERTY(m_flNoiseScaleLoc,IDENTITY(particleslib::CPerParticleFloatInput), 0x1900);
			NESTED_PROPERTY(m_TransformInput,IDENTITY(particleslib::CParticleTransformInput), 0x1a70);
			PROPERTY(m_bIgnoreDt,bool, 0x1ad8);
			S2_PAD(0x1900);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_InitialVelocityNoise) == 0x1AE0, "C_INIT_InitialVelocityNoise size should be 0x1AE0");

#endif
	}
}
