// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particles/SnapshotIndexType_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_InitSkinnedPositionFromCPSnapshot : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_nSnapshotControlPointNumber,int32_t, 0x1d8);
			PROPERTY(m_nControlPointNumber,int32_t, 0x1dc);
			PROPERTY(m_bRandom,bool, 0x1e0);
			PROPERTY(m_nRandomSeed,int32_t, 0x1e4);
			PROPERTY(m_bRigid,bool, 0x1e8);
			PROPERTY(m_bSetNormal,bool, 0x1e9);
			PROPERTY(m_bIgnoreDt,bool, 0x1ea);
			PROPERTY(m_flMinNormalVelocity,float32, 0x1ec);
			PROPERTY(m_flMaxNormalVelocity,float32, 0x1f0);
			PROPERTY(m_nIndexType,particles::SnapshotIndexType_t, 0x1f4);
			NESTED_PROPERTY(m_flReadIndex,particleslib::CPerParticleFloatInput, 0x1f8);
			PROPERTY(m_flIncrement,float32, 0x368);
			PROPERTY(m_nFullLoopIncrement,int32_t, 0x36c);
			PROPERTY(m_nSnapShotStartPoint,int32_t, 0x370);
			PROPERTY(m_flBoneVelocity,float32, 0x374);
			PROPERTY(m_flBoneVelocityMax,float32, 0x378);
			PROPERTY(m_bCopyColor,bool, 0x37c);
			PROPERTY(m_bCopyAlpha,bool, 0x37d);
			PROPERTY(m_bSetRadius,bool, 0x37e);
			S2_PAD(0x1A8);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_InitSkinnedPositionFromCPSnapshot) == 0x380, "C_INIT_InitSkinnedPositionFromCPSnapshot size should be 0x380");
	}
}
