// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particles/CRandomNumberGeneratorParameters.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_OffsetVectorToVector : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_nFieldInput,particles::ParticleAttributeIndex_t, 0x1d8);
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x1dc);
			PROPERTY(m_vecOutputMin,GlobalTypes::Vector, 0x1e0);
			PROPERTY(m_vecOutputMax,GlobalTypes::Vector, 0x1ec);
			NESTED_PROPERTY(m_randomnessParameters,particles::CRandomNumberGeneratorParameters, 0x1f8);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_OffsetVectorToVector) == 0x200, "C_INIT_OffsetVectorToVector size should be 0x200");
	}
}
