// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>
#include <SDK/particles/ParticleSetMethod_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_RemapTransformToVector : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x1d8);
			PROPERTY(m_vInputMin,GlobalTypes::Vector, 0x1dc);
			PROPERTY(m_vInputMax,GlobalTypes::Vector, 0x1e8);
			PROPERTY(m_vOutputMin,GlobalTypes::Vector, 0x1f4);
			PROPERTY(m_vOutputMax,GlobalTypes::Vector, 0x200);
			NESTED_PROPERTY(m_TransformInput,particleslib::CParticleTransformInput, 0x210);
			NESTED_PROPERTY(m_LocalSpaceTransform,particleslib::CParticleTransformInput, 0x278);
			PROPERTY(m_flStartTime,float32, 0x2e0);
			PROPERTY(m_flEndTime,float32, 0x2e4);
			PROPERTY(m_nSetMethod,particles::ParticleSetMethod_t, 0x2e8);
			PROPERTY(m_bOffset,bool, 0x2ec);
			PROPERTY(m_bAccelerate,bool, 0x2ed);
			PROPERTY(m_flRemapBias,float32, 0x2f0);
			S2_PAD(0x120);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_RemapTransformToVector) == 0x2F8, "C_INIT_RemapTransformToVector size should be 0x2F8");
	}
}
