// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_InitFloatCollection : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_InputValue,particleslib::CParticleCollectionFloatInput, 0x1d8);
			NESTED_PROPERTY(m_nOutputField,particles::ParticleAttributeIndex_t, 0x348);
			S2_PAD(0x178);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_InitFloatCollection) == 0x350, "C_INIT_InitFloatCollection size should be 0x350");
	}
}
