// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_PositionWarp : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_vecWarpMin,particleslib::CParticleCollectionVecInput, 0x1d8);
			NESTED_PROPERTY(m_vecWarpMax,particleslib::CParticleCollectionVecInput, 0x890);
			PROPERTY(m_nScaleControlPointNumber,int32_t, 0xf48);
			PROPERTY(m_nControlPointNumber,int32_t, 0xf4c);
			PROPERTY(m_nRadiusComponent,int32_t, 0xf50);
			PROPERTY(m_flWarpTime,float32, 0xf54);
			PROPERTY(m_flWarpStartTime,float32, 0xf58);
			PROPERTY(m_flPrevPosScale,float32, 0xf5c);
			PROPERTY(m_bInvertWarp,bool, 0xf60);
			PROPERTY(m_bUseCount,bool, 0xf61);
			S2_PAD(0xD90);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_PositionWarp) == 0xF68, "C_INIT_PositionWarp size should be 0xF68");
	}
}
