// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/ParticleSetMethod_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_DistanceToNeighborCull : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_flDistance,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e0);
			PROPERTY(m_bIncludeRadii,bool, 0x350);
			NESTED_PROPERTY(m_flLifespanOverlap,IDENTITY(particleslib::CPerParticleFloatInput), 0x358);
			NESTED_PROPERTY(m_nFieldModify,IDENTITY(particles::ParticleAttributeIndex_t), 0x4c8);
			NESTED_PROPERTY(m_flModify,IDENTITY(particleslib::CPerParticleFloatInput), 0x4d0);
			PROPERTY(m_nSetMethod,IDENTITY(particleslib::ParticleSetMethod_t), 0x640);
			PROPERTY(m_bUseNeighbor,bool, 0x644);
			S2_PAD(0x468);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_DistanceToNeighborCull) == 0x648, "C_INIT_DistanceToNeighborCull size should be 0x648");

#endif
	}
}
