// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCModel;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_RandomNamedModelElement : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_hModel,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCModel>, 0x1d8);
			PROPERTY(m_names,GlobalTypes::CUtlVector<GlobalTypes::CUtlString>, 0x1e0);
			PROPERTY(m_bShuffle,bool, 0x1f8);
			PROPERTY(m_bLinear,bool, 0x1f9);
			PROPERTY(m_bModelFromRenderer,bool, 0x1fa);
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x1fc);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::particles::C_INIT_RandomNamedModelElement) == 0x200, "C_INIT_RandomNamedModelElement size should be 0x200");
	}
}
