// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particles/CRandomNumberGeneratorParameters.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_AddVectorToVector : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_vecScale,GlobalTypes::Vector, 0x1e0);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1ec);
			NESTED_PROPERTY(m_nFieldInput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1f0);
			PROPERTY(m_vOffsetMin,GlobalTypes::Vector, 0x1f4);
			PROPERTY(m_vOffsetMax,GlobalTypes::Vector, 0x200);
			NESTED_PROPERTY(m_randomnessParameters,IDENTITY(particles::CRandomNumberGeneratorParameters), 0x20c);
			S2_PAD(0x38);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_AddVectorToVector) == 0x218, "C_INIT_AddVectorToVector size should be 0x218");

#endif
	}
}
