// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateFromCPs : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_nIncrement,int32_t, 0x1e0);
			PROPERTY(m_nMinCP,int32_t, 0x1e4);
			PROPERTY(m_nMaxCP,int32_t, 0x1e8);
			NESTED_PROPERTY(m_nDynamicCPCount,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1f0);
			S2_PAD(0x180);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_CreateFromCPs) == 0x360, "C_INIT_CreateFromCPs size should be 0x360");

#endif
	}
}
