// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_SequenceFromCP : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_bKillUnused,bool, 0x1e0);
			PROPERTY(m_bRadiusScale,bool, 0x1e1);
			PROPERTY(m_nCP,int32_t, 0x1e4);
			PROPERTY(m_vecOffset,GlobalTypes::Vector, 0x1e8);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_SequenceFromCP) == 0x1F8, "C_INIT_SequenceFromCP size should be 0x1F8");

#endif
	}
}
