// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particles/CPathParameters.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateSequentialPathV2 : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_fMaxDistance,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e0);
			NESTED_PROPERTY(m_flNumToAssign,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x350);
			PROPERTY(m_bLoop,bool, 0x4c0);
			PROPERTY(m_bCPPairs,bool, 0x4c1);
			PROPERTY(m_bSaveOffset,bool, 0x4c2);
			NESTED_PROPERTY(m_PathParams,IDENTITY(particles::CPathParameters), 0x4d0);
			S2_PAD(0x340);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_CreateSequentialPathV2) == 0x520, "C_INIT_CreateSequentialPathV2 size should be 0x520");

#endif
	}
}
