// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateWithinSphereTransform : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_fRadiusMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e0);
			NESTED_PROPERTY(m_fRadiusMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x350);
			NESTED_PROPERTY(m_vecDistanceBias,IDENTITY(particleslib::CPerParticleVecInput), 0x4c0);
			PROPERTY(m_vecDistanceBiasAbs,GlobalTypes::Vector, 0xb78);
			NESTED_PROPERTY(m_TransformInput,IDENTITY(particleslib::CParticleTransformInput), 0xb88);
			NESTED_PROPERTY(m_fSpeedMin,IDENTITY(particleslib::CPerParticleFloatInput), 0xbf0);
			NESTED_PROPERTY(m_fSpeedMax,IDENTITY(particleslib::CPerParticleFloatInput), 0xd60);
			PROPERTY(m_fSpeedRandExp,float32, 0xed0);
			PROPERTY(m_bLocalCoords,bool, 0xed4);
			NESTED_PROPERTY(m_LocalCoordinateSystemSpeedMin,IDENTITY(particleslib::CPerParticleVecInput), 0xed8);
			NESTED_PROPERTY(m_LocalCoordinateSystemSpeedMax,IDENTITY(particleslib::CPerParticleVecInput), 0x1590);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1c48);
			NESTED_PROPERTY(m_nFieldVelocity,IDENTITY(particles::ParticleAttributeIndex_t), 0x1c4c);
			S2_PAD(0x1A70);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_CreateWithinSphereTransform) == 0x1C50, "C_INIT_CreateWithinSphereTransform size should be 0x1C50");

#endif
	}
}
