// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>
#include <SDK/particles/ParticleSelection_t.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particles/ParticlePinDistance_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_PinParticleToCP : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nControlPointNumber,int32_t, 0x1d8);
			NESTED_PROPERTY(m_vecOffset,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1e0);
			PROPERTY(m_bOffsetLocal,bool, 0x898);
			PROPERTY(m_nParticleSelection,IDENTITY(particles::ParticleSelection_t), 0x89c);
			NESTED_PROPERTY(m_nParticleNumber,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x8a0);
			PROPERTY(m_nPinBreakType,IDENTITY(particles::ParticlePinDistance_t), 0xa10);
			NESTED_PROPERTY(m_flBreakDistance,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xa18);
			NESTED_PROPERTY(m_flBreakSpeed,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xb88);
			NESTED_PROPERTY(m_flAge,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xcf8);
			PROPERTY(m_nBreakControlPointNumber,int32_t, 0xe68);
			PROPERTY(m_nBreakControlPointNumber2,int32_t, 0xe6c);
			NESTED_PROPERTY(m_flBreakValue,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xe70);
			NESTED_PROPERTY(m_flInterpolation,IDENTITY(particleslib::CPerParticleFloatInput), 0xfe0);
			PROPERTY(m_bRetainInitialVelocity,bool, 0x1150);
			S2_PAD(0xF80);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_PinParticleToCP) == 0x1158, "C_OP_PinParticleToCP size should be 0x1158");

#endif
	}
}
