// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ConstrainDistance : public CS2::particles::CParticleFunctionConstraint {
		public:
			NESTED_PROPERTY(m_fMinDistance,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1d8);
			NESTED_PROPERTY(m_fMaxDistance,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x348);
			PROPERTY(m_nControlPointNumber,int32_t, 0x4b8);
			PROPERTY(m_CenterOffset,GlobalTypes::Vector, 0x4bc);
			PROPERTY(m_bGlobalCenter,bool, 0x4c8);
			S2_PAD(0x2F8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_ConstrainDistance) == 0x4D0, "C_OP_ConstrainDistance size should be 0x4D0");

#endif
	}
}
