// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionForce.hpp>
#include <SDK/particles/ParticleDirectionNoiseType_t.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_CurlNoiseForce : public CS2::particles::CParticleFunctionForce {
		public:
			PROPERTY(m_nNoiseType,particles::ParticleDirectionNoiseType_t, 0x1e0);
			NESTED_PROPERTY(m_vecNoiseFreq,particleslib::CPerParticleVecInput, 0x1e8);
			NESTED_PROPERTY(m_vecNoiseScale,particleslib::CPerParticleVecInput, 0x8a0);
			NESTED_PROPERTY(m_vecOffset,particleslib::CPerParticleVecInput, 0xf58);
			NESTED_PROPERTY(m_vecOffsetRate,particleslib::CPerParticleVecInput, 0x1610);
			NESTED_PROPERTY(m_flWorleySeed,particleslib::CPerParticleFloatInput, 0x1cc8);
			NESTED_PROPERTY(m_flWorleyJitter,particleslib::CPerParticleFloatInput, 0x1e38);
			S2_PAD(0x1DC8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_CurlNoiseForce) == 0x1FA8, "C_OP_CurlNoiseForce size should be 0x1FA8");
	}
}
