// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particles/EventTypeSelection_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetUserEvent : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_flInput,particleslib::CPerParticleFloatInput, 0x1d0);
			NESTED_PROPERTY(m_flRisingEdge,particleslib::CPerParticleFloatInput, 0x340);
			PROPERTY(m_nRisingEventType,particles::EventTypeSelection_t, 0x4b0);
			NESTED_PROPERTY(m_flFallingEdge,particleslib::CPerParticleFloatInput, 0x4b8);
			PROPERTY(m_nFallingEventType,particles::EventTypeSelection_t, 0x628);
			S2_PAD(0x460);
		};
		//static_assert(sizeof(CS2::particles::C_OP_SetUserEvent) == 0x630, "C_OP_SetUserEvent size should be 0x630");
	}
}
