// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_DragRelativeToPlane : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_flDragAtPlane,particleslib::CParticleCollectionFloatInput, 0x1d0);
			NESTED_PROPERTY(m_flFalloff,particleslib::CParticleCollectionFloatInput, 0x340);
			PROPERTY(m_bDirectional,bool, 0x4b0);
			NESTED_PROPERTY(m_vecPlaneNormal,particleslib::CParticleCollectionVecInput, 0x4b8);
			PROPERTY(m_nControlPointNumber,int32_t, 0xb70);
			S2_PAD(0x9A8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_DragRelativeToPlane) == 0xB78, "C_OP_DragRelativeToPlane size should be 0xB78");
	}
}
