// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_Decay : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_bRopeDecay,bool, 0x1d0);
			PROPERTY(m_bForcePreserveParticleOrder,bool, 0x1d1);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_Decay) == 0x1D8, "C_OP_Decay size should be 0x1D8");
	}
}
