// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_DecayClampCount : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nCount,particleslib::CParticleCollectionFloatInput, 0x1d0);
			S2_PAD(0x170);
		};
		//static_assert(sizeof(CS2::particles::C_OP_DecayClampCount) == 0x340, "C_OP_DecayClampCount size should be 0x340");
	}
}
