// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionRenderer.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RenderFlattenGrass : public CS2::particles::CParticleFunctionRenderer {
		public:
			PROPERTY(m_flFlattenStrength,float32, 0x228);
			NESTED_PROPERTY(m_nStrengthFieldOverride,IDENTITY(particles::ParticleAttributeIndex_t), 0x22c);
			PROPERTY(m_flRadiusScale,float32, 0x230);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RenderFlattenGrass) == 0x238, "C_OP_RenderFlattenGrass size should be 0x238");

#endif
	}
}
