// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/C_OP_RemapNamedModelElementEndCap.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapNamedModelBodyPartEndCap : public CS2::particles::C_OP_RemapNamedModelElementEndCap {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RemapNamedModelBodyPartEndCap) == 0x238, "C_OP_RemapNamedModelBodyPartEndCap size should be 0x238");

#endif
	}
}
