// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_LerpToInitialPosition : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nControlPointNumber,int32_t, 0x1d0);
			NESTED_PROPERTY(m_flInterpolation,particleslib::CPerParticleFloatInput, 0x1d8);
			NESTED_PROPERTY(m_nCacheField,particles::ParticleAttributeIndex_t, 0x348);
			NESTED_PROPERTY(m_flScale,particleslib::CParticleCollectionFloatInput, 0x350);
			NESTED_PROPERTY(m_vecScale,particleslib::CParticleCollectionVecInput, 0x4c0);
			S2_PAD(0x9A8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_LerpToInitialPosition) == 0xB78, "C_OP_LerpToInitialPosition size should be 0xB78");
	}
}
