// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RopeSpringConstraint : public CS2::particles::CParticleFunctionConstraint {
		public:
			NESTED_PROPERTY(m_flRestLength,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1d8);
			NESTED_PROPERTY(m_flMinDistance,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x348);
			NESTED_PROPERTY(m_flMaxDistance,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x4b8);
			PROPERTY(m_flAdjustmentScale,float32, 0x628);
			NESTED_PROPERTY(m_flInitialRestingLength,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x630);
			S2_PAD(0x5C8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RopeSpringConstraint) == 0x7A0, "C_OP_RopeSpringConstraint size should be 0x7A0");

#endif
	}
}
