// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_VectorFieldSnapshot : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nControlPointNumber,int32_t, 0x1d8);
			NESTED_PROPERTY(m_nAttributeToWrite,IDENTITY(particles::ParticleAttributeIndex_t), 0x1dc);
			PROPERTY(m_nLocalSpaceCP,int32_t, 0x1e0);
			NESTED_PROPERTY(m_flInterpolation,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e8);
			NESTED_PROPERTY(m_vecScale,IDENTITY(particleslib::CPerParticleVecInput), 0x358);
			PROPERTY(m_flBoundaryDampening,float32, 0xa10);
			PROPERTY(m_bSetVelocity,bool, 0xa14);
			PROPERTY(m_bLockToSurface,bool, 0xa15);
			PROPERTY(m_flGridSpacing,float32, 0xa18);
			S2_PAD(0x848);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_VectorFieldSnapshot) == 0xA20, "C_OP_VectorFieldSnapshot size should be 0xA20");

#endif
	}
}
