// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RampScalarLinearSimple : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_Rate,float32, 0x1d8);
			PROPERTY(m_flStartTime,float32, 0x1dc);
			PROPERTY(m_flEndTime,float32, 0x1e0);
			NESTED_PROPERTY(m_nField,IDENTITY(particles::ParticleAttributeIndex_t), 0x210);
			S2_PAD(0x48);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RampScalarLinearSimple) == 0x220, "C_OP_RampScalarLinearSimple size should be 0x220");

#endif
	}
}
