// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_CollideWithParentParticles : public CS2::particles::CParticleFunctionConstraint {
		public:
			NESTED_PROPERTY(m_flParentRadiusScale,particleslib::CPerParticleFloatInput, 0x1d0);
			NESTED_PROPERTY(m_flRadiusScale,particleslib::CPerParticleFloatInput, 0x340);
			S2_PAD(0x2E0);
		};
		//static_assert(sizeof(CS2::particles::C_OP_CollideWithParentParticles) == 0x4B0, "C_OP_CollideWithParentParticles size should be 0x4B0");
	}
}
