// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_OscillateVector : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_RateMin,GlobalTypes::Vector, 0x1d0);
			PROPERTY(m_RateMax,GlobalTypes::Vector, 0x1dc);
			PROPERTY(m_FrequencyMin,GlobalTypes::Vector, 0x1e8);
			PROPERTY(m_FrequencyMax,GlobalTypes::Vector, 0x1f4);
			NESTED_PROPERTY(m_nField,particles::ParticleAttributeIndex_t, 0x200);
			PROPERTY(m_bProportional,bool, 0x204);
			PROPERTY(m_bProportionalOp,bool, 0x205);
			PROPERTY(m_bOffset,bool, 0x206);
			PROPERTY(m_flStartTime_min,float32, 0x208);
			PROPERTY(m_flStartTime_max,float32, 0x20c);
			PROPERTY(m_flEndTime_min,float32, 0x210);
			PROPERTY(m_flEndTime_max,float32, 0x214);
			NESTED_PROPERTY(m_flOscMult,particleslib::CPerParticleFloatInput, 0x218);
			NESTED_PROPERTY(m_flOscAdd,particleslib::CPerParticleFloatInput, 0x388);
			NESTED_PROPERTY(m_flRateScale,particleslib::CPerParticleFloatInput, 0x4f8);
			S2_PAD(0x498);
		};
		//static_assert(sizeof(CS2::particles::C_OP_OscillateVector) == 0x668, "C_OP_OscillateVector size should be 0x668");
	}
}
