// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleSetMethod_t.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapTransformVisibilityToScalar : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nSetMethod,particles::ParticleSetMethod_t, 0x1d0);
			NESTED_PROPERTY(m_TransformInput,particleslib::CParticleTransformInput, 0x1d8);
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x240);
			PROPERTY(m_flInputMin,float32, 0x244);
			PROPERTY(m_flInputMax,float32, 0x248);
			PROPERTY(m_flOutputMin,float32, 0x24c);
			PROPERTY(m_flOutputMax,float32, 0x250);
			PROPERTY(m_flRadius,float32, 0x254);
			S2_PAD(0x88);
		};
		//static_assert(sizeof(CS2::particles::C_OP_RemapTransformVisibilityToScalar) == 0x258, "C_OP_RemapTransformVisibilityToScalar size should be 0x258");
	}
}
