// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>
#include <SDK/particles/PointDefinitionWithTimeValues_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ConstrainDistanceToUserSpecifiedPath : public CS2::particles::CParticleFunctionConstraint {
		public:
			PROPERTY(m_fMinDistance,float32, 0x1d8);
			PROPERTY(m_flMaxDistance,float32, 0x1dc);
			PROPERTY(m_flTimeScale,float32, 0x1e0);
			PROPERTY(m_bLoopedPath,bool, 0x1e4);
			NESTED_PROPERTY(m_pointList,IDENTITY(GlobalTypes::CUtlVector<particles::PointDefinitionWithTimeValues_t>), 0x1e8);
			S2_PAD(0x28);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_ConstrainDistanceToUserSpecifiedPath) == 0x200, "C_OP_ConstrainDistanceToUserSpecifiedPath size should be 0x200");

#endif
	}
}
