// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionPreEmission.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapExternalWindToCP : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nCP,int32_t, 0x1e0);
			PROPERTY(m_nCPOutput,int32_t, 0x1e4);
			NESTED_PROPERTY(m_vecScale,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1e8);
			PROPERTY(m_bSetMagnitude,bool, 0x8a0);
			PROPERTY(m_nOutVectorField,int32_t, 0x8a4);
			S2_PAD(0x6C8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RemapExternalWindToCP) == 0x8A8, "C_OP_RemapExternalWindToCP size should be 0x8A8");

#endif
	}
}
