// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_LerpScalar : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x1d0);
			NESTED_PROPERTY(m_flOutput,particleslib::CPerParticleFloatInput, 0x1d8);
			PROPERTY(m_flStartTime,float32, 0x348);
			PROPERTY(m_flEndTime,float32, 0x34c);
			S2_PAD(0x180);
		};
		//static_assert(sizeof(CS2::particles::C_OP_LerpScalar) == 0x350, "C_OP_LerpScalar size should be 0x350");
	}
}
