// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionForce.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RandomForce : public CS2::particles::CParticleFunctionForce {
		public:
			PROPERTY(m_MinForce,GlobalTypes::Vector, 0x1e8);
			PROPERTY(m_MaxForce,GlobalTypes::Vector, 0x1f4);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RandomForce) == 0x200, "C_OP_RandomForce size should be 0x200");

#endif
	}
}
