// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>
#include <SDK/particles/ParticleTraceSet_t.hpp>
#include <SDK/particleslib/ParticleSetMethod_t.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_DistanceToTransform : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d8);
			NESTED_PROPERTY(m_flInputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e0);
			NESTED_PROPERTY(m_flInputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x350);
			NESTED_PROPERTY(m_flOutputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x4c0);
			NESTED_PROPERTY(m_flOutputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x630);
			NESTED_PROPERTY(m_TransformStart,IDENTITY(particleslib::CParticleTransformInput), 0x7a0);
			PROPERTY(m_bLOS,bool, 0x808);
			PROPERTY_ARRAY(m_CollisionGroupName,char, 128 , 0x809);
			PROPERTY(m_nTraceSet,IDENTITY(particles::ParticleTraceSet_t), 0x88c);
			PROPERTY(m_flMaxTraceLength,float32, 0x890);
			PROPERTY(m_flLOSScale,float32, 0x894);
			PROPERTY(m_nSetMethod,IDENTITY(particleslib::ParticleSetMethod_t), 0x898);
			PROPERTY(m_bActiveRange,bool, 0x89c);
			PROPERTY(m_bAdditive,bool, 0x89d);
			NESTED_PROPERTY(m_vecComponentScale,IDENTITY(particleslib::CPerParticleVecInput), 0x8a0);
			S2_PAD(0xD80);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_DistanceToTransform) == 0xF58, "C_OP_DistanceToTransform size should be 0xF58");

#endif
	}
}
