// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/C_OP_RemapDistanceToLineSegmentBase.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapDistanceToLineSegmentToVector : public CS2::particles::C_OP_RemapDistanceToLineSegmentBase {
		public:
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1f0);
			PROPERTY(m_vMinOutputValue,GlobalTypes::Vector, 0x1f4);
			PROPERTY(m_vMaxOutputValue,GlobalTypes::Vector, 0x200);
			S2_PAD(0x20);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RemapDistanceToLineSegmentToVector) == 0x210, "C_OP_RemapDistanceToLineSegmentToVector size should be 0x210");

#endif
	}
}
