// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ColorAdjustHSL : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_flHueAdjust,particleslib::CPerParticleFloatInput, 0x1d0);
			NESTED_PROPERTY(m_flSaturationAdjust,particleslib::CPerParticleFloatInput, 0x340);
			NESTED_PROPERTY(m_flLightnessAdjust,particleslib::CPerParticleFloatInput, 0x4b0);
			S2_PAD(0x450);
		};
		//static_assert(sizeof(CS2::particles::C_OP_ColorAdjustHSL) == 0x620, "C_OP_ColorAdjustHSL size should be 0x620");
	}
}
