// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RopeSpringConstraint : public CS2::particles::CParticleFunctionConstraint {
		public:
			NESTED_PROPERTY(m_flRestLength,particleslib::CParticleCollectionFloatInput, 0x1d0);
			NESTED_PROPERTY(m_flMinDistance,particleslib::CParticleCollectionFloatInput, 0x340);
			NESTED_PROPERTY(m_flMaxDistance,particleslib::CParticleCollectionFloatInput, 0x4b0);
			PROPERTY(m_flAdjustmentScale,float32, 0x620);
			NESTED_PROPERTY(m_flInitialRestingLength,particleslib::CParticleCollectionFloatInput, 0x628);
			S2_PAD(0x5C8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_RopeSpringConstraint) == 0x798, "C_OP_RopeSpringConstraint size should be 0x798");
	}
}
