// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionPreEmission.hpp>
#include <SDK/particles/VectorExpressionType_t.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetControlPointToVectorExpression : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nExpression,IDENTITY(particles::VectorExpressionType_t), 0x1e0);
			PROPERTY(m_nOutputCP,int32_t, 0x1e4);
			NESTED_PROPERTY(m_vInput1,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1e8);
			NESTED_PROPERTY(m_vInput2,IDENTITY(particleslib::CParticleCollectionVecInput), 0x8a0);
			NESTED_PROPERTY(m_flLerp,IDENTITY(particleslib::CPerParticleFloatInput), 0xf58);
			PROPERTY(m_bNormalizedOutput,bool, 0x10c8);
			S2_PAD(0xEF0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetControlPointToVectorExpression) == 0x10D0, "C_OP_SetControlPointToVectorExpression size should be 0x10D0");

#endif
	}
}
