// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionForce.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CPerParticleVecInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_PerParticleForce : public CS2::particles::CParticleFunctionForce {
		public:
			NESTED_PROPERTY(m_flForceScale,particleslib::CPerParticleFloatInput, 0x1e0);
			NESTED_PROPERTY(m_vForce,particleslib::CPerParticleVecInput, 0x350);
			PROPERTY(m_nCP,int32_t, 0xa08);
			S2_PAD(0x830);
		};
		//static_assert(sizeof(CS2::particles::C_OP_PerParticleForce) == 0xA10, "C_OP_PerParticleForce size should be 0xA10");
	}
}
