// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionConstraint.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ConstrainLineLength : public CS2::particles::CParticleFunctionConstraint {
		public:
			PROPERTY(m_flMinDistance,float32, 0x1d0);
			PROPERTY(m_flMaxDistance,float32, 0x1d4);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::particles::C_OP_ConstrainLineLength) == 0x1D8, "C_OP_ConstrainLineLength size should be 0x1D8");
	}
}
