// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionPreEmission.hpp>
#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>
#include <SDK/particles/ParticleLightnintBranchBehavior_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_LightningSnapshotGenerator : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nCPSnapshot,int32_t, 0x1e0);
			PROPERTY(m_nCPStartPnt,int32_t, 0x1e4);
			PROPERTY(m_nCPEndPnt,int32_t, 0x1e8);
			NESTED_PROPERTY(m_flSegments,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1f0);
			NESTED_PROPERTY(m_flOffset,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x360);
			NESTED_PROPERTY(m_flOffsetDecay,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x4d0);
			NESTED_PROPERTY(m_flRecalcRate,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x640);
			NESTED_PROPERTY(m_flUVScale,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x7b0);
			NESTED_PROPERTY(m_flUVOffset,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x920);
			NESTED_PROPERTY(m_flSplitRate,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xa90);
			NESTED_PROPERTY(m_flBranchTwist,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xc00);
			PROPERTY(m_nBranchBehavior,IDENTITY(particles::ParticleLightnintBranchBehavior_t), 0xd70);
			NESTED_PROPERTY(m_flRadiusStart,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xd78);
			NESTED_PROPERTY(m_flRadiusEnd,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xee8);
			NESTED_PROPERTY(m_flDedicatedPool,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1058);
			S2_PAD(0xFE8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_LightningSnapshotGenerator) == 0x11C8, "C_OP_LightningSnapshotGenerator size should be 0x11C8");

#endif
	}
}
