// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionOperator.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>
#include <SDK/particleslib/CPerParticleFloatInput.hpp>
#include <SDK/particleslib/CParticleTransformInput.hpp>
#include <SDK/particles/ParticleSetMethod_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_CylindricalDistanceToTransform : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nFieldOutput,particles::ParticleAttributeIndex_t, 0x1d0);
			NESTED_PROPERTY(m_flInputMin,particleslib::CPerParticleFloatInput, 0x1d8);
			NESTED_PROPERTY(m_flInputMax,particleslib::CPerParticleFloatInput, 0x348);
			NESTED_PROPERTY(m_flOutputMin,particleslib::CPerParticleFloatInput, 0x4b8);
			NESTED_PROPERTY(m_flOutputMax,particleslib::CPerParticleFloatInput, 0x628);
			NESTED_PROPERTY(m_TransformStart,particleslib::CParticleTransformInput, 0x798);
			NESTED_PROPERTY(m_TransformEnd,particleslib::CParticleTransformInput, 0x800);
			PROPERTY(m_nSetMethod,particles::ParticleSetMethod_t, 0x868);
			PROPERTY(m_bActiveRange,bool, 0x86c);
			PROPERTY(m_bAdditive,bool, 0x86d);
			PROPERTY(m_bCapsule,bool, 0x86e);
			S2_PAD(0x6A0);
		};
		//static_assert(sizeof(CS2::particles::C_OP_CylindricalDistanceToTransform) == 0x870, "C_OP_CylindricalDistanceToTransform size should be 0x870");
	}
}
