// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class CPathParameters  {
		public:
			PROPERTY(m_nStartControlPointNumber,int32_t, 0x0);
			PROPERTY(m_nEndControlPointNumber,int32_t, 0x4);
			PROPERTY(m_nBulgeControl,int32_t, 0x8);
			PROPERTY(m_flBulge,float32, 0xc);
			PROPERTY(m_flMidPoint,float32, 0x10);
			PROPERTY(m_vStartPointOffset,GlobalTypes::Vector, 0x14);
			PROPERTY(m_vMidPointOffset,GlobalTypes::Vector, 0x20);
			PROPERTY(m_vEndOffset,GlobalTypes::Vector, 0x2c);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::particles::CPathParameters) == 0x40, "CPathParameters size should be 0x40");
	}
}
