// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/PetGroundType_t.hpp>
#include <SDK/particles/ParticlePreviewBodyGroup_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class ParticlePreviewState_t  {
		public:
			PROPERTY(m_previewModel,GlobalTypes::CUtlString*, 0x0);
			PROPERTY(m_nModSpecificData,uint32_t, 0x8);
			PROPERTY(m_groundType,particles::PetGroundType_t, 0xc);
			PROPERTY(m_sequenceName,GlobalTypes::CUtlString*, 0x10);
			PROPERTY(m_nFireParticleOnSequenceFrame,int32_t, 0x18);
			PROPERTY(m_hitboxSetName,GlobalTypes::CUtlString*, 0x20);
			PROPERTY(m_materialGroupName,GlobalTypes::CUtlString*, 0x28);
			NESTED_PROPERTY(m_vecBodyGroups,GlobalTypes::CUtlVector<particles::ParticlePreviewBodyGroup_t>, 0x30);
			PROPERTY(m_flPlaybackSpeed,float32, 0x48);
			PROPERTY(m_flParticleSimulationRate,float32, 0x4c);
			PROPERTY(m_bShouldDrawHitboxes,bool, 0x50);
			PROPERTY(m_bShouldDrawAttachments,bool, 0x51);
			PROPERTY(m_bShouldDrawAttachmentNames,bool, 0x52);
			PROPERTY(m_bShouldDrawControlPointAxes,bool, 0x53);
			PROPERTY(m_bAnimationNonLooping,bool, 0x54);
			PROPERTY(m_bSequenceNameIsAnimClipPath,bool, 0x55);
			PROPERTY(m_vecPreviewGravity,GlobalTypes::Vector, 0x58);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::particles::ParticlePreviewState_t) == 0x68, "ParticlePreviewState_t size should be 0x68");
	}
}
