// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace particles {
		enum ParticleToolsState_t : std::uint32_t {
			ParticleToolsState_t_PARTICLE_TOOLS_STATE_ALWAYS_ON = 0xffffffff,
			ParticleToolsState_t_PARTICLE_TOOLS_STATE_GAME_ONLY = 0x1,
			ParticleToolsState_t_PARTICLE_TOOLS_STATE_TOOLS_ONLY = 0x0
		};
	}
}