// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class ParticlePreviewBodyGroup_t  {
		public:
			PROPERTY(m_bodyGroupName,GlobalTypes::CUtlString*, 0x0);
			PROPERTY(m_nValue,int32_t, 0x8);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::particles::ParticlePreviewBodyGroup_t) == 0x10, "ParticlePreviewBodyGroup_t size should be 0x10");
	}
}
