// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/physicslib/FeBoxRigid_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class FeBuildBoxRigid_t : public CS2::physicslib::FeBoxRigid_t {
		public:
			PROPERTY(m_nPriority,int32_t, 0x40);
			PROPERTY(m_nVertexMapHash,uint32_t, 0x44);
			PROPERTY(m_nAntitunnelGroupBits,uint32_t, 0x48);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::physicslib::FeBuildBoxRigid_t) == 0x50, "FeBuildBoxRigid_t size should be 0x50");
	}
}
