// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class FeFitMatrix_t  {
		public:
			PROPERTY(bone,GlobalTypes::CTransform, 0x0);
			PROPERTY(vCenter,GlobalTypes::Vector, 0x20);
			PROPERTY(nEnd,uint16_t, 0x2c);
			PROPERTY(nNode,uint16_t, 0x2e);
			PROPERTY(nBeginDynamic,uint16_t, 0x30);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::physicslib::FeFitMatrix_t) == 0x40, "FeFitMatrix_t size should be 0x40");
	}
}
