// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class FeWeightedNode_t  {
		public:
			PROPERTY(nNode,uint16_t, 0x0);
			PROPERTY(nWeight,uint16_t, 0x2);
			S2_PAD(0x4);
		};
		//static_assert(sizeof(CS2::physicslib::FeWeightedNode_t) == 0x4, "FeWeightedNode_t size should be 0x4");
	}
}
