// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class RnPlane_t  {
		public:
			PROPERTY(m_vNormal,GlobalTypes::Vector, 0x0);
			PROPERTY(m_flOffset,float32, 0xc);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::physicslib::RnPlane_t) == 0x10, "RnPlane_t size should be 0x10");
	}
}
