// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class RnVertex_t  {
		public:
			PROPERTY(m_nEdge,uint8_t, 0x0);
			S2_PAD(0x1);
		};
		//static_assert(sizeof(CS2::physicslib::RnVertex_t) == 0x1, "RnVertex_t size should be 0x1");
	}
}
