// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/scenesystem/SceneViewId_t.hpp>
#include <SDK/scenesystem/CSSDSMsg_ViewTarget.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace scenesystem {
		class CSSDSMsg_ViewTargetList  {
		public:
			NESTED_PROPERTY(m_viewId,scenesystem::SceneViewId_t, 0x0);
			PROPERTY(m_ViewName,GlobalTypes::CUtlString*, 0x10);
			NESTED_PROPERTY(m_Targets,GlobalTypes::CUtlVector<scenesystem::CSSDSMsg_ViewTarget>, 0x18);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::scenesystem::CSSDSMsg_ViewTargetList) == 0x30, "CSSDSMsg_ViewTargetList size should be 0x30");
	}
}
