// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class AI_Navigator_DebugSnapshotData_t_Waypoint_t  {
		public:
			PROPERTY(position,GlobalTypes::VectorWS, 0x0);
			PROPERTY(nav_type,uint32_t, 0xc);
			PROPERTY(flags,uint32_t, 0x10);
			S2_PAD(0x14);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::AI_Navigator_DebugSnapshotData_t_Waypoint_t) == 0x14, "AI_Navigator_DebugSnapshotData_t::Waypoint_t size should be 0x14");

#endif
	}
}
