// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class AmmoIndex_t  {
		public:
			PROPERTY(m_Value,int8_t, 0x0);
			S2_PAD(0x1);
		};
		//static_assert(sizeof(CS2::client::AmmoIndex_t) == 0x1, "AmmoIndex_t size should be 0x1");
	}
}
