// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_BaseClientUIEntity : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_bEnabled,bool, 0xfb0);
			PROPERTY(m_DialogXMLName,GlobalTypes::CUtlSymbolLarge*, 0xfb8);
			PROPERTY(m_PanelClassName,GlobalTypes::CUtlSymbolLarge*, 0xfc0);
			PROPERTY(m_PanelID,GlobalTypes::CUtlSymbolLarge*, 0xfc8);
			S2_PAD(0x30);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_BaseClientUIEntity) == 0xFD8, "C_BaseClientUIEntity size should be 0xFD8");

#endif
	}
}
