// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>
#include <SDK/client/C_EconItemView.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSGO_TeamPreviewCharacterPosition : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_nVariant,int32_t, 0x600);
			PROPERTY(m_nRandom,int32_t, 0x604);
			PROPERTY(m_nOrdinal,int32_t, 0x608);
			PROPERTY(m_sWeaponName,GlobalTypes::CUtlString*, 0x610);
			PROPERTY(m_xuid,uint64_t, 0x618);
			NESTED_PROPERTY(m_agentItem,IDENTITY(client::C_EconItemView), 0x620);
			NESTED_PROPERTY(m_glovesItem,IDENTITY(client::C_EconItemView), 0xa90);
			NESTED_PROPERTY(m_weaponItem,IDENTITY(client::C_EconItemView), 0xf00);
			S2_PAD(0xDA0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSGO_TeamPreviewCharacterPosition) == 0x13A0, "C_CSGO_TeamPreviewCharacterPosition size should be 0x13A0");

#endif
	}
}
