// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BasePlayerPawn.hpp>
#include <SDK/client/CSPlayerState.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace client {
		class CCSPlayer_PingServices;
		class CCSPlayerController;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSPlayerPawnBase : public CS2::client::C_BasePlayerPawn {
		public:
			PROPERTY(m_pPingServices,IDENTITY(client::CCSPlayer_PingServices*), 0x13c8);
			PROPERTY(m_previousPlayerState,IDENTITY(client::CSPlayerState), 0x13d0);
			PROPERTY(m_iPlayerState,IDENTITY(client::CSPlayerState), 0x13d4);
			PROPERTY(m_bHasMovedSinceSpawn,bool, 0x13d8);
			NESTED_PROPERTY(m_flLastSpawnTimeIndex,IDENTITY(entity2::GameTime_t), 0x13dc);
			PROPERTY(m_iProgressBarDuration,int32_t, 0x13e0);
			PROPERTY(m_flProgressBarStartTime,float32, 0x13e4);
			NESTED_PROPERTY(m_flClientDeathTime,IDENTITY(entity2::GameTime_t), 0x13e8);
			PROPERTY(m_flFlashBangTime,float32, 0x13ec);
			PROPERTY(m_flFlashScreenshotAlpha,float32, 0x13f0);
			PROPERTY(m_flFlashOverlayAlpha,float32, 0x13f4);
			PROPERTY(m_bFlashBuildUp,bool, 0x13f8);
			PROPERTY(m_bFlashDspHasBeenCleared,bool, 0x13f9);
			PROPERTY(m_bFlashScreenshotHasBeenGrabbed,bool, 0x13fa);
			PROPERTY(m_flFlashMaxAlpha,float32, 0x13fc);
			PROPERTY(m_flFlashDuration,float32, 0x1400);
			NESTED_PROPERTY(m_flClientHealthFadeChangeTimestamp,IDENTITY(entity2::GameTime_t), 0x1404);
			PROPERTY(m_nClientHealthFadeParityValue,int32_t, 0x1408);
			PROPERTY(m_fNextThinkPushAway,float32, 0x140c);
			PROPERTY(m_flCurrentMusicStartTime,float32, 0x1414);
			PROPERTY(m_flMusicRoundStartTime,float32, 0x1418);
			PROPERTY(m_bDeferStartMusicOnWarmup,bool, 0x141c);
			PROPERTY(m_flLastSmokeOverlayAlpha,float32, 0x1420);
			PROPERTY(m_flLastSmokeAge,float32, 0x1424);
			PROPERTY(m_vLastSmokeOverlayColor,GlobalTypes::Vector, 0x1428);
			PROPERTY(m_hOriginalController,IDENTITY(GlobalTypes::CHandle<client::CCSPlayerController>), 0x1450);
			S2_PAD(0xA0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSPlayerPawnBase) == 0x1458, "C_CSPlayerPawnBase size should be 0x1458");

#endif
	}
}
