// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_GameRulesProxy.hpp>



namespace CS2 {
	namespace client {
		class C_CSGameRules;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSGameRulesProxy : public CS2::client::C_GameRulesProxy {
		public:
			PROPERTY(m_pGameRules,IDENTITY(client::C_CSGameRules*), 0x600);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSGameRulesProxy) == 0x608, "C_CSGameRulesProxy size should be 0x608");

#endif
	}
}
