// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSPlayerResource : public CS2::client::C_BaseEntity {
		public:
			PROPERTY_ARRAY(m_bHostageAlive,bool, 12 , 0x608);
			PROPERTY_ARRAY(m_isHostageFollowingSomeone,bool, 12 , 0x614);
			PROPERTY_ARRAY(m_iHostageEntityIDs,GlobalTypes::CEntityIndex, 12 , 0x620);
			PROPERTY(m_bombsiteCenterA,GlobalTypes::Vector, 0x650);
			PROPERTY(m_bombsiteCenterB,GlobalTypes::Vector, 0x65c);
			PROPERTY_ARRAY(m_hostageRescueX,int32_t, 4 , 0x668);
			PROPERTY_ARRAY(m_hostageRescueY,int32_t, 4 , 0x678);
			PROPERTY_ARRAY(m_hostageRescueZ,int32_t, 4 , 0x688);
			PROPERTY(m_bEndMatchNextMapAllVoted,bool, 0x698);
			PROPERTY(m_foundGoalPositions,bool, 0x699);
			S2_PAD(0x98);
		};
		//static_assert(sizeof(CS2::client::C_CSPlayerResource) == 0x6A0, "C_CSPlayerResource size should be 0x6A0");
	}
}
