// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EnvWindShared  {
		public:
			NESTED_PROPERTY(m_flStartTime,entity2::GameTime_t, 0x8);
			PROPERTY(m_iWindSeed,uint32_t, 0xc);
			PROPERTY(m_iMinWind,uint16_t, 0x10);
			PROPERTY(m_iMaxWind,uint16_t, 0x12);
			PROPERTY(m_windRadius,int32_t, 0x14);
			PROPERTY(m_iMinGust,uint16_t, 0x18);
			PROPERTY(m_iMaxGust,uint16_t, 0x1a);
			PROPERTY(m_flMinGustDelay,float32, 0x1c);
			PROPERTY(m_flMaxGustDelay,float32, 0x20);
			PROPERTY(m_flGustDuration,float32, 0x24);
			PROPERTY(m_iGustDirChange,uint16_t, 0x28);
			PROPERTY(m_iInitialWindDir,uint16_t, 0x2a);
			PROPERTY(m_flInitialWindSpeed,float32, 0x2c);
			PROPERTY(m_location,GlobalTypes::Vector, 0x30);
			PROPERTY(m_hEntOwner,GlobalTypes::CHandle<client::C_BaseEntity>, 0x3c);
			S2_PAD(0xF8);
		};
		//static_assert(sizeof(CS2::client::C_EnvWindShared) == 0xF8, "C_EnvWindShared size should be 0xF8");
	}
}
