// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_FuncTrackTrain : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_nLongAxis,int32_t, 0xe88);
			PROPERTY(m_flRadius,float32, 0xe8c);
			PROPERTY(m_flLineLength,float32, 0xe90);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::client::C_FuncTrackTrain) == 0xE98, "C_FuncTrackTrain size should be 0xE98");
	}
}
