// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_HandleTest : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_Handle,GlobalTypes::CHandle<client::C_BaseEntity>, 0x608);
			PROPERTY(m_bSendHandle,bool, 0x60c);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::client::C_HandleTest) == 0x610, "C_HandleTest size should be 0x610");
	}
}
