// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>



namespace CS2 {
	namespace client {
		class CLightComponent;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_LightEntity : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_CLightComponent,client::CLightComponent*, 0xe88);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::client::C_LightEntity) == 0xE90, "C_LightEntity size should be 0xE90");
	}
}
