// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CBaseAnimGraph.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_RagdollProp : public CS2::client::CBaseAnimGraph {
		public:
			PROPERTY(m_ragEnabled,GlobalTypes::C_NetworkUtlVectorBase< bool >, 0x1170);
			PROPERTY(m_ragPos,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::Vector>, 0x1188);
			PROPERTY(m_ragAngles,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::QAngle>, 0x11a0);
			PROPERTY(m_flBlendWeight,float32, 0x11b8);
			PROPERTY(m_hRagdollSource,GlobalTypes::CHandle<client::C_BaseEntity>, 0x11bc);
			NESTED_PROPERTY(m_iEyeAttachment,modellib::AttachmentHandle_t, 0x11c0);
			PROPERTY(m_flBlendWeightCurrent,float32, 0x11c4);
			NESTED_PROPERTY(m_parentPhysicsBoneIndices,GlobalTypes::CUtlVector< int32 >, 0x11c8);
			NESTED_PROPERTY(m_worldSpaceBoneComputationOrder,GlobalTypes::CUtlVector< int32 >, 0x11e0);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::client::C_RagdollProp) == 0x11F8, "C_RagdollProp size should be 0x11F8");
	}
}
