// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_SpotlightEnd : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_flLightScale,float32, 0xfa8);
			PROPERTY(m_Radius,float32, 0xfac);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_SpotlightEnd) == 0xFB8, "C_SpotlightEnd size should be 0xFB8");

#endif
	}
}
