// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_VoteController : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_iActiveIssueIndex,int32_t, 0x618);
			PROPERTY(m_iOnlyTeamToVote,int32_t, 0x61c);
			PROPERTY_ARRAY(m_nVoteOptionCount,int32_t, 5 , 0x620);
			PROPERTY(m_nPotentialVotes,int32_t, 0x634);
			PROPERTY(m_bVotesDirty,bool, 0x638);
			PROPERTY(m_bTypeDirty,bool, 0x639);
			PROPERTY(m_bIsYesNoVote,bool, 0x63a);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::client::C_VoteController) == 0x640, "C_VoteController size should be 0x640");
	}
}
