// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace client {
		class CAnimGraphControllerBase;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CAnimGraphControllerManager  {
		public:
			NESTED_PROPERTY(m_controllers,GlobalTypes::CUtlVector<client::CAnimGraphControllerBase*>, 0x0);
			PROPERTY(m_bGraphBindingsCreated,bool, 0xa8);
			S2_PAD(0xB0);
		};
		//static_assert(sizeof(CS2::client::CAnimGraphControllerManager) == 0xB0, "CAnimGraphControllerManager size should be 0xB0");
	}
}
