// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/client/SellbackPurchaseEntry_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CCSPlayer_BuyServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_vecSellbackPurchaseEntries,GlobalTypes::C_UtlVectorEmbeddedNetworkVar<client::SellbackPurchaseEntry_t>, 0x48);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::client::CCSPlayer_BuyServices) == 0xB0, "CCSPlayer_BuyServices size should be 0xB0");
	}
}
