// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace client {
		enum CCSPlayerAnimationState_AirAction_t : std::uint8_t {
			CCSPlayerAnimationState_AirAction_t_Jump = 0x1,
			CCSPlayerAnimationState_AirAction_t_Land = 0x3,
			CCSPlayerAnimationState_AirAction_t_None = 0x0,
			CCSPlayerAnimationState_AirAction_t_StartFall = 0x2
		};
	}
}