// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace client {
		enum CCSPlayerAnimationState_MoveType_t : std::uint8_t {
			CCSPlayerAnimationState_MoveType_t_Air = 0x2,
			CCSPlayerAnimationState_MoveType_t_Ground = 0x1,
			CCSPlayerAnimationState_MoveType_t_Ladder = 0x3,
			CCSPlayerAnimationState_MoveType_t_None = 0x0
		};
	}
}