// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayer_WeaponServices.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CCSPlayer_WeaponServices : public CS2::client::CPlayer_WeaponServices {
		public:
			NESTED_PROPERTY(m_flNextAttack,IDENTITY(entity2::GameTime_t), 0xd0);
			PROPERTY(m_nOldTotalShootPositionHistoryCount,uint32_t, 0xd4);
			PROPERTY(m_nOldTotalInputHistoryCount,uint32_t, 0x370);
			// PROPERTY(m_networkAnimTiming,IDENTITY(GlobalTypes::C_NetworkUtlVectorBase< uint8 >), 0x1588);
			PROPERTY(m_bBlockInspectUntilNextGraphUpdate,bool, 0x15a0);
			S2_PAD(0x1528);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CCSPlayer_WeaponServices) == 0x15D0, "CCSPlayer_WeaponServices size should be 0x15D0");

#endif
	}
}
