// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/DecalGroupOption_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CDecalGroupVData  {
		public:
			NESTED_PROPERTY(m_vecOptions,GlobalTypes::CUtlVector<client::DecalGroupOption_t>, 0x0);
			PROPERTY(m_flTotalProbability,float32, 0x18);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::client::CDecalGroupVData) == 0x20, "CDecalGroupVData size should be 0x20");
	}
}
