// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/CNetworkVarChainer.hpp>



namespace CS2 {
	namespace client {
		class C_BaseModelEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CDestructiblePartsComponent  {
		public:
			NESTED_PROPERTY(__m_pChainEntity,entity2::CNetworkVarChainer, 0x0);
			NESTED_PROPERTY(m_vecDamageTakenByHitGroup,GlobalTypes::CUtlVector< uint16 >, 0x48);
			PROPERTY(m_hOwner,GlobalTypes::CHandle<client::C_BaseModelEntity>, 0x60);
			S2_PAD(0x70);
		};
		//static_assert(sizeof(CS2::client::CDestructiblePartsComponent) == 0x70, "CDestructiblePartsComponent size should be 0x70");
	}
}
