// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CEnvSoundscape.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CEnvSoundscapeTriggerable : public CS2::client::CEnvSoundscape {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CEnvSoundscapeTriggerable) == 0x690, "CEnvSoundscapeTriggerable size should be 0x690");

#endif
	}
}
