// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/client/GrenadeType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CGrenadeTracer : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_flTracerDuration,float32, 0xea0);
			PROPERTY(m_nType,client::GrenadeType_t, 0xea4);
			S2_PAD(0x498);
		};
		//static_assert(sizeof(CS2::client::CGrenadeTracer) == 0x1320, "CGrenadeTracer size should be 0x1320");
	}
}
