// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/InventoryNodeType_t.hpp>
#include <SDK/client/inv_image_data_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CInventoryImageData  {
		public:
			PROPERTY(m_nNodeType,client::InventoryNodeType_t, 0x0);
			PROPERTY(name,GlobalTypes::CUtlString*, 0x8);
			NESTED_PROPERTY(inventory_image_data,client::inv_image_data_t, 0x10);
			S2_PAD(0xF8);
		};
		//static_assert(sizeof(CS2::client::CInventoryImageData) == 0xF8, "CInventoryImageData size should be 0xF8");
	}
}
