// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCModel;
	}
	namespace vphysics2 {
		class IPhysAggregateInstance;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CModelState  {
		public:
			PROPERTY(m_hModel,IDENTITY(GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCModel>), 0xa0);
			PROPERTY(m_ModelName,GlobalTypes::CUtlSymbolLarge*, 0xa8);
			PROPERTY(m_pVPhysicsAggregate,IDENTITY(vphysics2::IPhysAggregateInstance*), 0xe0);
			PROPERTY(m_flRootBoneOffset_x,float32, 0xe8);
			PROPERTY(m_flRootBoneOffset_y,float32, 0xec);
			PROPERTY(m_flRootBoneOffset_z,float32, 0xf0);
			PROPERTY(m_nRootBoneOffsetResetSerialNumber,uint8_t, 0xf4);
			PROPERTY(m_bClientClothCreationSuppressed,bool, 0x110);
			PROPERTY(m_nAnimStateNoInterpSerialNumber,uint8_t, 0x1c0);
			PROPERTY(m_MeshGroupMask,uint64_t, 0x1c8);
			// PROPERTY(m_nBodyGroupChoices,IDENTITY(GlobalTypes::C_NetworkUtlVectorBase< int32 >), 0x218);
			PROPERTY(m_nIdealMotionType,int8_t, 0x262);
			PROPERTY(m_nForceLOD,int8_t, 0x263);
			PROPERTY(m_nClothUpdateFlags,int8_t, 0x264);
			S2_PAD(0x270);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CModelState) == 0x270, "CModelState size should be 0x270");

#endif
	}
}
