// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CountdownTimer  {
		public:
			PROPERTY(m_duration,float32, 0x8);
			NESTED_PROPERTY(m_timestamp,entity2::GameTime_t, 0xc);
			PROPERTY(m_timescale,float32, 0x10);
			PROPERTY(m_nWorldGroupId,GlobalTypes::WorldGroupId_t, 0x14);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::client::CountdownTimer) == 0x18, "CountdownTimer size should be 0x18");
	}
}
