// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/client/ObserverMode_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CPlayer_ObserverServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_iObserverMode,uint8_t, 0x48);
			PROPERTY(m_hObserverTarget,GlobalTypes::CHandle<client::C_BaseEntity>, 0x4c);
			PROPERTY(m_iObserverLastMode,client::ObserverMode_t, 0x50);
			PROPERTY(m_bForcedObserverMode,bool, 0x54);
			PROPERTY(m_flObserverChaseDistance,float32, 0x58);
			NESTED_PROPERTY(m_flObserverChaseDistanceCalcTime,entity2::GameTime_t, 0x5c);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::client::CPlayer_ObserverServices) == 0x60, "CPlayer_ObserverServices size should be 0x60");
	}
}
