// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_PointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CPointChildModifier : public CS2::client::C_PointEntity {
		public:
			PROPERTY(m_bOrphanInsteadOfDeletingChildrenOnRemove,bool, 0x608);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::client::CPointChildModifier) == 0x610, "CPointChildModifier size should be 0x610");
	}
}
