// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CSoundEnvelope.hpp>
#include <SDK/client/CCopyRecipientFilter.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CSoundPatch  {
		public:
			NESTED_PROPERTY(m_pitch,client::CSoundEnvelope, 0x8);
			NESTED_PROPERTY(m_volume,client::CSoundEnvelope, 0x18);
			PROPERTY(m_shutdownTime,float32, 0x3c);
			PROPERTY(m_flLastTime,float32, 0x40);
			PROPERTY(m_iszSoundScriptName,GlobalTypes::CUtlSymbolLarge*, 0x48);
			PROPERTY(m_hEnt,GlobalTypes::CHandle<client::C_BaseEntity>, 0x50);
			PROPERTY(m_soundEntityIndex,GlobalTypes::CEntityIndex, 0x54);
			PROPERTY(m_soundOrigin,GlobalTypes::Vector, 0x58);
			PROPERTY(m_isPlaying,int32_t, 0x64);
			NESTED_PROPERTY(m_Filter,client::CCopyRecipientFilter, 0x68);
			PROPERTY(m_flCloseCaptionDuration,float32, 0xa0);
			PROPERTY(m_bUpdatedSoundOrigin,bool, 0xa4);
			PROPERTY(m_iszClassName,GlobalTypes::CUtlSymbolLarge*, 0xa8);
			S2_PAD(0xB0);
		};
		//static_assert(sizeof(CS2::client::CSoundPatch) == 0xB0, "CSoundPatch size should be 0xB0");
	}
}
