// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/HitGroup_t.hpp>



namespace CS2 {
	namespace client {
		class CTakeDamageInfo;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CTakeDamageResult  {
		public:
			PROPERTY(m_pOriginatingInfo,client::CTakeDamageInfo*, 0x0);
			PROPERTY(m_nHealthLost,int32_t, 0x8);
			PROPERTY(m_nHealthBefore,int32_t, 0xc);
			PROPERTY(m_nDamageDealt,int32_t, 0x10);
			PROPERTY(m_flPreModifiedDamage,float32, 0x14);
			PROPERTY(m_nTotalledHealthLost,int32_t, 0x18);
			PROPERTY(m_nTotalledDamageDealt,int32_t, 0x1c);
			PROPERTY(m_flTotalledPreModifiedDamage,float32, 0x20);
			PROPERTY(m_bWasDamageSuppressed,bool, 0x24);
			PROPERTY(m_bSuppressFlinch,bool, 0x25);
			PROPERTY(m_nOverrideFlinchHitGroup,client::HitGroup_t, 0x28);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::client::CTakeDamageResult) == 0x30, "CTakeDamageResult size should be 0x30");
	}
}
