// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace client {
		enum ESceneRequestState_t : std::uint32_t {
			ESceneRequestState_t_ACTIVE = 0x1,
			ESceneRequestState_t_FAILED = 0x3,
			ESceneRequestState_t_FINISHED = 0x2,
			ESceneRequestState_t_INACTIVE = 0x0
		};
	}
}