// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/EngineLoopState_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class EventClientFrameSimulate_t  {
		public:
			NESTED_PROPERTY(m_LoopState,client::EngineLoopState_t, 0x0);
			PROPERTY(m_flRealTime,float32, 0x28);
			PROPERTY(m_flFrameTime,float32, 0x2c);
			PROPERTY(m_bScheduleSendTickPacket,bool, 0x30);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::client::EventClientFrameSimulate_t) == 0x38, "EventClientFrameSimulate_t size should be 0x38");
	}
}
