// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/EngineLoopState_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class EventSetTime_t  {
		public:
			NESTED_PROPERTY(m_LoopState,client::EngineLoopState_t, 0x0);
			PROPERTY(m_nClientOutputFrames,int32_t, 0x28);
			PROPERTY(m_flRealTime,float64, 0x30);
			PROPERTY(m_flRenderTime,float64, 0x38);
			PROPERTY(m_flRenderFrameTime,float64, 0x40);
			PROPERTY(m_flRenderFrameTimeUnbounded,float64, 0x48);
			PROPERTY(m_flRenderFrameTimeUnscaled,float64, 0x50);
			PROPERTY(m_flTickRemainder,float64, 0x58);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::client::EventSetTime_t) == 0x60, "EventSetTime_t size should be 0x60");
	}
}
