// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class EventClientProcessNetworking_t  {
		public:
			PROPERTY(m_nTickCount,int32_t, 0x0);
			S2_PAD(0x4);
		};
		//static_assert(sizeof(CS2::client::EventClientProcessNetworking_t) == 0x4, "EventClientProcessNetworking_t size should be 0x4");
	}
}
