// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class fogparams_t  {
		public:
			PROPERTY(dirPrimary,GlobalTypes::Vector, 0x8);
			PROPERTY(colorPrimary,GlobalTypes::Color, 0x14);
			PROPERTY(colorSecondary,GlobalTypes::Color, 0x18);
			PROPERTY(colorPrimaryLerpTo,GlobalTypes::Color, 0x1c);
			PROPERTY(colorSecondaryLerpTo,GlobalTypes::Color, 0x20);
			PROPERTY(start,float32, 0x24);
			PROPERTY(end,float32, 0x28);
			PROPERTY(farz,float32, 0x2c);
			PROPERTY(maxdensity,float32, 0x30);
			PROPERTY(exponent,float32, 0x34);
			PROPERTY(HDRColorScale,float32, 0x38);
			PROPERTY(skyboxFogFactor,float32, 0x3c);
			PROPERTY(skyboxFogFactorLerpTo,float32, 0x40);
			PROPERTY(startLerpTo,float32, 0x44);
			PROPERTY(endLerpTo,float32, 0x48);
			PROPERTY(maxdensityLerpTo,float32, 0x4c);
			NESTED_PROPERTY(lerptime,entity2::GameTime_t, 0x50);
			PROPERTY(duration,float32, 0x54);
			PROPERTY(blendtobackground,float32, 0x58);
			PROPERTY(scattering,float32, 0x5c);
			PROPERTY(locallightscale,float32, 0x60);
			PROPERTY(enable,bool, 0x64);
			PROPERTY(blend,bool, 0x65);
			PROPERTY(m_bPadding2,bool, 0x66);
			PROPERTY(m_bPadding,bool, 0x67);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::client::fogparams_t) == 0x68, "fogparams_t size should be 0x68");
	}
}
