// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace client {
		class ResponseFollowup;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class ResponseParams  {
		public:
			PROPERTY(odds,int16_t, 0x10);
			PROPERTY(flags,int16_t, 0x12);
			PROPERTY(m_pFollowup,client::ResponseFollowup*, 0x18);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::client::ResponseParams) == 0x20, "ResponseParams size should be 0x20");
	}
}
