// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class SAVE_HEADER  {
		public:
			PROPERTY(m_saveId,int32_t, 0x0);
			PROPERTY(m_version,int32_t, 0x4);
			PROPERTY(m_nConnectionCount,int32_t, 0x8);
			PROPERTY(m_nMapVersion,int32_t, 0xc);
			PROPERTY(m_sSpawnGroupName,GlobalTypes::CUtlString*, 0x10);
			PROPERTY(m_vecWorldOffset,GlobalTypes::matrix3x4a_t, 0x20);
			PROPERTY(m_flSaveTime,float32, 0x50);
			S2_PAD(0x60);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::SAVE_HEADER) == 0x60, "SAVE_HEADER size should be 0x60");

#endif
	}
}
