// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class screenshake_t  {
		public:
			NESTED_PROPERTY(endtime,IDENTITY(entity2::GameTime_t), 0x0);
			PROPERTY(duration,float32, 0x4);
			PROPERTY(amplitude,float32, 0x8);
			PROPERTY(frequency,float32, 0xc);
			NESTED_PROPERTY(nextShake,IDENTITY(entity2::GameTime_t), 0x10);
			PROPERTY(offset,GlobalTypes::Vector, 0x14);
			PROPERTY(angle,float32, 0x20);
			PROPERTY(direction,GlobalTypes::Vector, 0x28);
			PROPERTY(nShakeType,uint8_t, 0x34);
			S2_PAD(0x38);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::screenshake_t) == 0x38, "screenshake_t size should be 0x38");

#endif
	}
}
