// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CTakeDamageInfo.hpp>
#include <SDK/client/CTakeDamageResult.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class SummaryTakeDamageInfo_t  {
		public:
			PROPERTY(nSummarisedCount,int32_t, 0x0);
			NESTED_PROPERTY(info,client::CTakeDamageInfo, 0x8);
			NESTED_PROPERTY(result,client::CTakeDamageResult, 0x128);
			PROPERTY(hTarget,GlobalTypes::CHandle<client::C_BaseEntity>, 0x158);
			S2_PAD(0x160);
		};
		//static_assert(sizeof(CS2::client::SummaryTakeDamageInfo_t) == 0x160, "SummaryTakeDamageInfo_t size should be 0x160");
	}
}
