// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem/CDSPMixgroupModifier.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem {
		class CDspPresetModifierList  {
		public:
			PROPERTY(m_dspName,GlobalTypes::CUtlString*, 0x0);
			NESTED_PROPERTY(m_modifiers,GlobalTypes::CUtlVector<soundsystem::CDSPMixgroupModifier>, 0x8);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::soundsystem::CDspPresetModifierList) == 0x20, "CDspPresetModifierList size should be 0x20");
	}
}
