// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem/CSosGroupActionSchema.hpp>
#include <SDK/soundsystem/SosActionStopType_t.hpp>
#include <SDK/soundsystem/SosActionLimitSortType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem {
		class CSosGroupActionLimitSchema : public CS2::soundsystem::CSosGroupActionSchema {
		public:
			PROPERTY(m_nMaxCount,int32_t, 0x8);
			PROPERTY(m_nStopType,soundsystem::SosActionStopType_t, 0xc);
			PROPERTY(m_nSortType,soundsystem::SosActionLimitSortType_t, 0x10);
			PROPERTY(m_bStopImmediate,bool, 0x14);
			PROPERTY(m_bCountStopped,bool, 0x15);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::soundsystem::CSosGroupActionLimitSchema) == 0x18, "CSosGroupActionLimitSchema size should be 0x18");
	}
}
