// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem/CSosGroupActionSchema.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem {
		class CSosGroupActionSoundeventCountSchema : public CS2::soundsystem::CSosGroupActionSchema {
		public:
			PROPERTY(m_bExcludeStoppedSounds,bool, 0x8);
			PROPERTY(m_strCountKeyName,GlobalTypes::CUtlString*, 0x10);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::soundsystem::CSosGroupActionSoundeventCountSchema) == 0x18, "CSosGroupActionSoundeventCountSchema size should be 0x18");
	}
}
