// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace soundsystem {
		class VelocityZone_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem {
		class KeyGroup_t  {
		public:
			PROPERTY(nCenterNote,uint8_t, 0x0);
			PROPERTY(nMinNote,uint8_t, 0x1);
			PROPERTY(nMaxNote,uint8_t, 0x2);
			PROPERTY(nNumVelocityZones,uint8_t, 0x3);
			PROPERTY(pVelocityZones,IDENTITY(soundsystem::VelocityZone_t*), 0x8);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::soundsystem::KeyGroup_t) == 0x10, "KeyGroup_t size should be 0x10");

#endif
	}
}
