// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animationsystem {
		class CAnimActivity  {
		public:
			PROPERTY(m_name,GlobalTypes::CBufferString, 0x0);
			PROPERTY(m_nActivity,int32_t, 0x10);
			PROPERTY(m_nFlags,int32_t, 0x14);
			PROPERTY(m_nWeight,int32_t, 0x18);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animationsystem::CAnimActivity) == 0x20, "CAnimActivity size should be 0x20");
	}
}
