// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CAI_ChangeHintGroup : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_iSearchType,int32_t, 0x4a8);
			PROPERTY(m_strSearchName,GlobalTypes::CUtlSymbolLarge*, 0x4b0);
			PROPERTY(m_strNewHintGroup,GlobalTypes::CUtlSymbolLarge*, 0x4b8);
			PROPERTY(m_flRadius,float32, 0x4c0);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::CAI_ChangeHintGroup) == 0x4C8, "CAI_ChangeHintGroup size should be 0x4C8");
	}
}
