// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCTextureBase;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBarnLight : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bEnabled,bool, 0x730);
			PROPERTY(m_nColorMode,int32_t, 0x734);
			PROPERTY(m_Color,GlobalTypes::Color, 0x738);
			PROPERTY(m_flColorTemperature,float32, 0x73c);
			PROPERTY(m_flBrightness,float32, 0x740);
			PROPERTY(m_flBrightnessScale,float32, 0x744);
			PROPERTY(m_nDirectLight,int32_t, 0x748);
			PROPERTY(m_nBakedShadowIndex,int32_t, 0x74c);
			PROPERTY(m_nLightPathUniqueId,int32_t, 0x750);
			PROPERTY(m_nLightMapUniqueId,int32_t, 0x754);
			PROPERTY(m_nLuminaireShape,int32_t, 0x758);
			PROPERTY(m_flLuminaireSize,float32, 0x75c);
			PROPERTY(m_flLuminaireAnisotropy,float32, 0x760);
			PROPERTY(m_LightStyleString,GlobalTypes::CUtlString*, 0x768);
			NESTED_PROPERTY(m_flLightStyleStartTime,entity2::GameTime_t, 0x770);
			PROPERTY(m_QueuedLightStyleStrings,GlobalTypes::CNetworkUtlVectorBase<GlobalTypes::CUtlString>, 0x778);
			PROPERTY(m_LightStyleEvents,GlobalTypes::CNetworkUtlVectorBase<GlobalTypes::CUtlString>, 0x790);
			PROPERTY(m_LightStyleTargets,server::CNetworkUtlVectorBase<GlobalTypes::CHandle<server::CBaseModelEntity>>, 0x7a8);
			PROPERTY_ARRAY(m_StyleEvent,entity2::CEntityIOOutput, 4 , 0x7c0);
			PROPERTY(m_hLightCookie,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x840);
			PROPERTY(m_flShape,float32, 0x848);
			PROPERTY(m_flSoftX,float32, 0x84c);
			PROPERTY(m_flSoftY,float32, 0x850);
			PROPERTY(m_flSkirt,float32, 0x854);
			PROPERTY(m_flSkirtNear,float32, 0x858);
			PROPERTY(m_vSizeParams,GlobalTypes::Vector, 0x85c);
			PROPERTY(m_flRange,float32, 0x868);
			PROPERTY(m_vShear,GlobalTypes::Vector, 0x86c);
			PROPERTY(m_nBakeSpecularToCubemaps,int32_t, 0x878);
			PROPERTY(m_vBakeSpecularToCubemapsSize,GlobalTypes::Vector, 0x87c);
			PROPERTY(m_nCastShadows,int32_t, 0x888);
			PROPERTY(m_nShadowMapSize,int32_t, 0x88c);
			PROPERTY(m_nShadowPriority,int32_t, 0x890);
			PROPERTY(m_bContactShadow,bool, 0x894);
			PROPERTY(m_bForceShadowsEnabled,bool, 0x895);
			PROPERTY(m_nBounceLight,int32_t, 0x898);
			PROPERTY(m_flBounceScale,float32, 0x89c);
			PROPERTY(m_bDynamicBounce,bool, 0x8a0);
			PROPERTY(m_flMinRoughness,float32, 0x8a4);
			PROPERTY(m_vAlternateColor,GlobalTypes::Vector, 0x8a8);
			PROPERTY(m_fAlternateColorBrightness,float32, 0x8b4);
			PROPERTY(m_nFog,int32_t, 0x8b8);
			PROPERTY(m_flFogStrength,float32, 0x8bc);
			PROPERTY(m_nFogShadows,int32_t, 0x8c0);
			PROPERTY(m_flFogScale,float32, 0x8c4);
			PROPERTY(m_bFogMixedShadows,bool, 0x8c8);
			PROPERTY(m_flFadeSizeStart,float32, 0x8cc);
			PROPERTY(m_flFadeSizeEnd,float32, 0x8d0);
			PROPERTY(m_flShadowFadeSizeStart,float32, 0x8d4);
			PROPERTY(m_flShadowFadeSizeEnd,float32, 0x8d8);
			PROPERTY(m_bPrecomputedFieldsValid,bool, 0x8dc);
			PROPERTY(m_vPrecomputedBoundsMins,GlobalTypes::Vector, 0x8e0);
			PROPERTY(m_vPrecomputedBoundsMaxs,GlobalTypes::Vector, 0x8ec);
			PROPERTY(m_vPrecomputedOBBOrigin,GlobalTypes::Vector, 0x8f8);
			PROPERTY(m_vPrecomputedOBBAngles,GlobalTypes::QAngle, 0x904);
			PROPERTY(m_vPrecomputedOBBExtent,GlobalTypes::Vector, 0x910);
			PROPERTY(m_nPrecomputedSubFrusta,int32_t, 0x91c);
			PROPERTY(m_vPrecomputedOBBOrigin0,GlobalTypes::Vector, 0x920);
			PROPERTY(m_vPrecomputedOBBAngles0,GlobalTypes::QAngle, 0x92c);
			PROPERTY(m_vPrecomputedOBBExtent0,GlobalTypes::Vector, 0x938);
			PROPERTY(m_vPrecomputedOBBOrigin1,GlobalTypes::Vector, 0x944);
			PROPERTY(m_vPrecomputedOBBAngles1,GlobalTypes::QAngle, 0x950);
			PROPERTY(m_vPrecomputedOBBExtent1,GlobalTypes::Vector, 0x95c);
			PROPERTY(m_vPrecomputedOBBOrigin2,GlobalTypes::Vector, 0x968);
			PROPERTY(m_vPrecomputedOBBAngles2,GlobalTypes::QAngle, 0x974);
			PROPERTY(m_vPrecomputedOBBExtent2,GlobalTypes::Vector, 0x980);
			PROPERTY(m_vPrecomputedOBBOrigin3,GlobalTypes::Vector, 0x98c);
			PROPERTY(m_vPrecomputedOBBAngles3,GlobalTypes::QAngle, 0x998);
			PROPERTY(m_vPrecomputedOBBExtent3,GlobalTypes::Vector, 0x9a4);
			PROPERTY(m_vPrecomputedOBBOrigin4,GlobalTypes::Vector, 0x9b0);
			PROPERTY(m_vPrecomputedOBBAngles4,GlobalTypes::QAngle, 0x9bc);
			PROPERTY(m_vPrecomputedOBBExtent4,GlobalTypes::Vector, 0x9c8);
			PROPERTY(m_vPrecomputedOBBOrigin5,GlobalTypes::Vector, 0x9d4);
			PROPERTY(m_vPrecomputedOBBAngles5,GlobalTypes::QAngle, 0x9e0);
			PROPERTY(m_vPrecomputedOBBExtent5,GlobalTypes::Vector, 0x9ec);
			PROPERTY(m_bPvsModifyEntity,bool, 0x9f8);
			PROPERTY(m_VisClusters,GlobalTypes::CNetworkUtlVectorBase< uint16 >, 0xa00);
			S2_PAD(0x2F0);
		};
		//static_assert(sizeof(CS2::server::CBarnLight) == 0xA20, "CBarnLight size should be 0xA20");
	}
}
