// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseFlex.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CCSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseGrenade : public CS2::server::CBaseFlex {
		public:
			NESTED_PROPERTY(m_OnPlayerPickup,entity2::CEntityIOOutput, 0xab8);
			NESTED_PROPERTY(m_OnExplode,entity2::CEntityIOOutput, 0xad0);
			PROPERTY(m_bHasWarnedAI,bool, 0xae8);
			PROPERTY(m_bIsSmokeGrenade,bool, 0xae9);
			PROPERTY(m_bIsLive,bool, 0xaea);
			PROPERTY(m_DmgRadius,float32, 0xaec);
			NESTED_PROPERTY(m_flDetonateTime,entity2::GameTime_t, 0xaf0);
			PROPERTY(m_flWarnAITime,float32, 0xaf4);
			PROPERTY(m_flDamage,float32, 0xaf8);
			PROPERTY(m_iszBounceSound,GlobalTypes::CUtlSymbolLarge*, 0xb00);
			PROPERTY(m_ExplosionSound,GlobalTypes::CUtlString*, 0xb08);
			PROPERTY(m_hThrower,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0xb14);
			NESTED_PROPERTY(m_flNextAttack,entity2::GameTime_t, 0xb2c);
			PROPERTY(m_hOriginalThrower,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0xb30);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::server::CBaseGrenade) == 0xB40, "CBaseGrenade size should be 0xB40");
	}
}
