// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CServerOnlyModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlace : public CS2::server::CServerOnlyModelEntity {
		public:
			PROPERTY(m_name,GlobalTypes::CUtlSymbolLarge*, 0x748);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::CCSPlace) == 0x750, "CCSPlace size should be 0x750");
	}
}
