// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/server/SellbackPurchaseEntry_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlayer_BuyServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_vecSellbackPurchaseEntries,server::CUtlVectorEmbeddedNetworkVar<server::SellbackPurchaseEntry_t>, 0xd0);
			S2_PAD(0x110);
		};
		//static_assert(sizeof(CS2::server::CCSPlayer_BuyServices) == 0x158, "CCSPlayer_BuyServices size should be 0x158");
	}
}
