// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/EKillTypes_t.hpp>



namespace CS2 {
	namespace server {
		class CCSPlayerPawn;
		class CCSPlayerController;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CDamageRecord  {
		public:
			PROPERTY(m_PlayerDamager,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0x30);
			PROPERTY(m_PlayerRecipient,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0x34);
			PROPERTY(m_hPlayerControllerDamager,GlobalTypes::CHandle<server::CCSPlayerController>, 0x38);
			PROPERTY(m_hPlayerControllerRecipient,GlobalTypes::CHandle<server::CCSPlayerController>, 0x3c);
			PROPERTY(m_szPlayerDamagerName,GlobalTypes::CUtlString*, 0x40);
			PROPERTY(m_szPlayerRecipientName,GlobalTypes::CUtlString*, 0x48);
			PROPERTY(m_DamagerXuid,uint64_t, 0x50);
			PROPERTY(m_RecipientXuid,uint64_t, 0x58);
			PROPERTY(m_flBulletsDamage,float32, 0x60);
			PROPERTY(m_flDamage,float32, 0x64);
			PROPERTY(m_flActualHealthRemoved,float32, 0x68);
			PROPERTY(m_iNumHits,int32_t, 0x6c);
			PROPERTY(m_iLastBulletUpdate,int32_t, 0x70);
			PROPERTY(m_bIsOtherEnemy,bool, 0x74);
			PROPERTY(m_killType,client::EKillTypes_t, 0x75);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::server::CDamageRecord) == 0x78, "CDamageRecord size should be 0x78");
	}
}
