// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/CNetworkVarChainer.hpp>



namespace CS2 {
	namespace server {
		class CBaseModelEntity;
	}
	namespace client {
		class CBaseAnimGraphDestructibleParts_GraphController;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CDestructiblePartsComponent  {
		public:
			NESTED_PROPERTY(__m_pChainEntity,IDENTITY(entity2::CNetworkVarChainer), 0x0);
			NESTED_PROPERTY(m_vecDamageTakenByHitGroup,IDENTITY(GlobalTypes::CUtlVector< uint16 >), 0x48);
			PROPERTY(m_hOwner,IDENTITY(GlobalTypes::CHandle<server::CBaseModelEntity>), 0x60);
			PROPERTY(m_pAnimGraphDestructibleGraphController,IDENTITY(client::CBaseAnimGraphDestructibleParts_GraphController*), 0x68);
			S2_PAD(0x70);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CDestructiblePartsComponent) == 0x70, "CDestructiblePartsComponent size should be 0x70");

#endif
	}
}
