// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvViewPunch : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_flRadius,float32, 0x4a8);
			PROPERTY(m_angViewPunch,GlobalTypes::QAngle, 0x4ac);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CEnvViewPunch) == 0x4B8, "CEnvViewPunch size should be 0x4B8");
	}
}
