// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvSplash : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_flScale,float32, 0x4a8);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CEnvSplash) == 0x4B0, "CEnvSplash size should be 0x4B0");
	}
}
