// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvBeverage : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_CanInDispenser,bool, 0x4a8);
			PROPERTY(m_nBeverageType,int32_t, 0x4ac);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CEnvBeverage) == 0x4B0, "CEnvBeverage size should be 0x4B0");
	}
}
