// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvEntityIgniter : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_flLifetime,float32, 0x4a8);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CEnvEntityIgniter) == 0x4B0, "CEnvEntityIgniter size should be 0x4B0");
	}
}
