// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/server/CFish.hpp>
#include <SDK/server/CountdownTimer.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFishPool : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_fishCount,int32_t, 0x4b8);
			PROPERTY(m_maxRange,float32, 0x4bc);
			PROPERTY(m_swimDepth,float32, 0x4c0);
			PROPERTY(m_waterLevel,float32, 0x4c4);
			PROPERTY(m_isDormant,bool, 0x4c8);
			NESTED_PROPERTY(m_fishes,server::CUtlVector<GlobalTypes::CHandle<server::CFish>>, 0x4d0);
			NESTED_PROPERTY(m_visTimer,server::CountdownTimer, 0x4e8);
			S2_PAD(0x58);
		};
		//static_assert(sizeof(CS2::server::CFishPool) == 0x500, "CFishPool size should be 0x500");
	}
}
