// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseCSGrenadeProjectile.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFlashbangProjectile : public CS2::server::CBaseCSGrenadeProjectile {
		public:
			PROPERTY(m_flTimeToDetonate,float32, 0xbb0);
			PROPERTY(m_numOpponentsHit,uint8_t, 0xbb4);
			PROPERTY(m_numTeammatesHit,uint8_t, 0xbb5);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CFlashbangProjectile) == 0xBC0, "CFlashbangProjectile size should be 0xBC0");
	}
}
