// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>
#include <SDK/server/fogparams_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFogTrigger : public CS2::server::CBaseTrigger {
		public:
			NESTED_PROPERTY(m_fog,server::fogparams_t, 0x890);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::server::CFogTrigger) == 0x8F8, "CFogTrigger size should be 0x8F8");
	}
}
