// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBasePlatTrain.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncTrain : public CS2::server::CBasePlatTrain {
		public:
			PROPERTY(m_hCurrentTarget,GlobalTypes::CHandle<server::CBaseEntity>, 0x7d8);
			PROPERTY(m_activated,bool, 0x7dc);
			PROPERTY(m_hEnemy,GlobalTypes::CHandle<server::CBaseEntity>, 0x7e0);
			PROPERTY(m_flBlockDamage,float32, 0x7e4);
			NESTED_PROPERTY(m_flNextBlockTime,entity2::GameTime_t, 0x7e8);
			PROPERTY(m_iszLastTarget,GlobalTypes::CUtlSymbolLarge*, 0x7f0);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::CFuncTrain) == 0x7F8, "CFuncTrain size should be 0x7F8");
	}
}
