// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncVPhysicsClip : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bDisabled,bool, 0x768);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CFuncVPhysicsClip) == 0x770, "CFuncVPhysicsClip size should be 0x770");

#endif
	}
}
