// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CItem.hpp>



namespace CS2 {
	namespace server {
		class CCSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItemDogtags : public CS2::server::CItem {
		public:
			PROPERTY(m_OwningPlayer,IDENTITY(GlobalTypes::CHandle<server::CCSPlayerPawn>), 0x9e0);
			PROPERTY(m_KillingPlayer,IDENTITY(GlobalTypes::CHandle<server::CCSPlayerPawn>), 0x9e4);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CItemDogtags) == 0x9F0, "CItemDogtags size should be 0x9F0");

#endif
	}
}
