// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CItem.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItemKevlar : public CS2::server::CItem {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CItemKevlar) == 0x9E0, "CItemKevlar size should be 0x9E0");

#endif
	}
}
