// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseAnimGraph.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItem : public CS2::server::CBaseAnimGraph {
		public:
			NESTED_PROPERTY(m_OnPlayerTouch,IDENTITY(entity2::CEntityIOOutput), 0x948);
			NESTED_PROPERTY(m_OnPlayerPickup,IDENTITY(entity2::CEntityIOOutput), 0x960);
			PROPERTY(m_bActivateWhenAtRest,bool, 0x978);
			NESTED_PROPERTY(m_OnCacheInteraction,IDENTITY(entity2::CEntityIOOutput), 0x980);
			NESTED_PROPERTY(m_OnGlovePulled,IDENTITY(entity2::CEntityIOOutput), 0x998);
			PROPERTY(m_vOriginalSpawnOrigin,GlobalTypes::VectorWS, 0x9b0);
			PROPERTY(m_vOriginalSpawnAngles,GlobalTypes::QAngle, 0x9bc);
			PROPERTY(m_bPhysStartAsleep,bool, 0x9c8);
			S2_PAD(0xA0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CItem) == 0x9E0, "CItem size should be 0x9E0");

#endif
	}
}
