// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>



namespace CS2 {
	namespace server {
		class CItemGeneric;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItemGenericTriggerHelper : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_hParentItem,IDENTITY(GlobalTypes::CHandle<server::CItemGeneric>), 0x768);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CItemGenericTriggerHelper) == 0x770, "CItemGenericTriggerHelper size should be 0x770");

#endif
	}
}
