// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CCSWeaponBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CKnife : public CS2::server::CCSWeaponBase {
		public:
			PROPERTY(m_bFirstAttack,bool, 0x1030);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CKnife) == 0x1040, "CKnife size should be 0x1040");

#endif
	}
}
