// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLightDirectionalEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLightEnvironmentEntity : public CS2::server::CLightDirectionalEntity {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CLightEnvironmentEntity) == 0x770, "CLightEnvironmentEntity size should be 0x770");

#endif
	}
}
