// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLogicCompare : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_flInValue,float32, 0x4a8);
			PROPERTY(m_flCompareValue,float32, 0x4ac);
			PROPERTY(m_OnLessThan,GlobalTypes::CEntityOutputTemplate< float32, float32 >, 0x4b0);
			PROPERTY(m_OnEqualTo,GlobalTypes::CEntityOutputTemplate< float32, float32 >, 0x4d0);
			PROPERTY(m_OnNotEqualTo,GlobalTypes::CEntityOutputTemplate< float32, float32 >, 0x4f0);
			PROPERTY(m_OnGreaterThan,GlobalTypes::CEntityOutputTemplate< float32, float32 >, 0x510);
			S2_PAD(0x88);
		};
		//static_assert(sizeof(CS2::server::CLogicCompare) == 0x530, "CLogicCompare size should be 0x530");
	}
}
