// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CMarkupVolumeWithRef.hpp>
#include <SDK/server/NavScopeFlags_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMarkupVolumeTagged_NavGame : public CS2::server::CMarkupVolumeWithRef {
		public:
			PROPERTY(m_nScopes,server::NavScopeFlags_t, 0x798);
			PROPERTY(m_bFloodFillAttribute,bool, 0x799);
			PROPERTY(m_bSplitNavSpace,bool, 0x79a);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CMarkupVolumeTagged_NavGame) == 0x7A0, "CMarkupVolumeTagged_NavGame size should be 0x7A0");
	}
}
