// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMathColorBlend : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_flInMin,float32, 0x4a8);
			PROPERTY(m_flInMax,float32, 0x4ac);
			PROPERTY(m_OutColor1,GlobalTypes::Color, 0x4b0);
			PROPERTY(m_OutColor2,GlobalTypes::Color, 0x4b4);
			PROPERTY(m_OutValue,GlobalTypes::CEntityOutputTemplate< Color, Color >, 0x4b8);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::server::CMathColorBlend) == 0x4D8, "CMathColorBlend size should be 0x4D8");
	}
}
