// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CAI_ExpresserWithFollowup.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMultiplayer_Expresser : public CS2::server::CAI_ExpresserWithFollowup {
		public:
			PROPERTY(m_bAllowMultipleScenes,bool, 0xa0);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CMultiplayer_Expresser) == 0xA8, "CMultiplayer_Expresser size should be 0xA8");

#endif
	}
}
