// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CPathMover;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPathMoverEntitySpawner : public CS2::server::CLogicalEntity {
		public:
			PROPERTY_ARRAY(m_szSpawnTemplates,GlobalTypes::CUtlSymbolLarge*, 4 , 0x4a8);
			PROPERTY(m_nSpawnIndex,int32_t, 0x4c8);
			PROPERTY(m_hPathMover,GlobalTypes::CHandle<server::CPathMover>, 0x4cc);
			PROPERTY(m_flSpawnFrequencySeconds,float32, 0x4d0);
			PROPERTY(m_flSpawnFrequencyDistToNearestMover,float32, 0x4d4);
			PROPERTY(m_mapSpawnedMoverTemplates,server::CUtlHashtable< CHandle< CFuncMover >, CPathMoverEntitySpawn >, 0x4d8);
			PROPERTY(m_nMaxActive,int32_t, 0x4f8);
			NESTED_PROPERTY(m_flLastSpawnTime,entity2::GameTime_t, 0x4fc);
			PROPERTY(m_bEnabled,bool, 0x500);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::server::CPathMoverEntitySpawner) == 0x508, "CPathMoverEntitySpawner size should be 0x508");
	}
}
