// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPathWithDynamicNodes.hpp>
#include <SDK/server/CFuncMover.hpp>



namespace CS2 {
	namespace server {
		class CPathMoverEntitySpawner;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPathMover : public CS2::server::CPathWithDynamicNodes {
		public:
			NESTED_PROPERTY(m_vecMovers,server::CUtlVector<GlobalTypes::CHandle<server::CFuncMover>>, 0x5f0);
			PROPERTY(m_hMoverSpawner,GlobalTypes::CHandle<server::CPathMoverEntitySpawner>, 0x608);
			PROPERTY(m_iszMoverSpawnerName,GlobalTypes::CUtlSymbolLarge*, 0x610);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::server::CPathMover) == 0x620, "CPathMover size should be 0x620");
	}
}
