// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>



namespace CS2 {
	namespace server {
		class CFuncPlat;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPlatTrigger : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_pPlatform,GlobalTypes::CHandle<server::CFuncPlat>, 0x730);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CPlatTrigger) == 0x738, "CPlatTrigger size should be 0x738");
	}
}
