// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/server/EntFinderMethod_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseFilter;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointEntityFinder : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_hEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x4a8);
			PROPERTY(m_iFilterName,GlobalTypes::CUtlSymbolLarge*, 0x4b0);
			PROPERTY(m_hFilter,GlobalTypes::CHandle<server::CBaseFilter>, 0x4b8);
			PROPERTY(m_iRefName,GlobalTypes::CUtlSymbolLarge*, 0x4c0);
			PROPERTY(m_hReference,GlobalTypes::CHandle<server::CBaseEntity>, 0x4c8);
			PROPERTY(m_FindMethod,server::EntFinderMethod_t, 0x4cc);
			NESTED_PROPERTY(m_OnFoundEntity,entity2::CEntityIOOutput, 0x4d0);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::server::CPointEntityFinder) == 0x4E8, "CPointEntityFinder size should be 0x4E8");
	}
}
