// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPulseCell_Outflow_PlayVOLine_CursorState_t  {
		public:
			PROPERTY(m_sceneInstance,IDENTITY(GlobalTypes::CHandle<server::CBaseEntity>), 0x0);
			S2_PAD(0x4);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CPulseCell_Outflow_PlayVOLine_CursorState_t) == 0x4, "CPulseCell_Outflow_PlayVOLine::CursorState_t size should be 0x4");

#endif
	}
}
