// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseExecCursor.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPulseServerCursor : public CS2::pulse_runtime_lib::CPulseExecCursor {
		public:
			PROPERTY(m_hActivator,IDENTITY(GlobalTypes::CHandle<server::CBaseEntity>), 0xe8);
			PROPERTY(m_hCaller,IDENTITY(GlobalTypes::CHandle<server::CBaseEntity>), 0xec);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CPulseServerCursor) == 0xF0, "CPulseServerCursor size should be 0xF0");

#endif
	}
}
