// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CTriggerMultiple.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CScriptTriggerMultiple : public CS2::server::CTriggerMultiple {
		public:
			PROPERTY(m_vExtent,GlobalTypes::Vector, 0x8e0);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CScriptTriggerMultiple) == 0x8F0, "CScriptTriggerMultiple size should be 0x8F0");

#endif
	}
}
