// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseCSGrenadeProjectile.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSmokeGrenadeProjectile : public CS2::server::CBaseCSGrenadeProjectile {
		public:
			PROPERTY(m_nSmokeEffectTickBegin,int32_t, 0xa58);
			PROPERTY(m_bDidSmokeEffect,bool, 0xa5c);
			PROPERTY(m_nRandomSeed,int32_t, 0xa60);
			PROPERTY(m_vSmokeColor,GlobalTypes::Vector, 0xa64);
			PROPERTY(m_vSmokeDetonationPos,GlobalTypes::Vector, 0xa70);
			// PROPERTY(m_VoxelFrameData,IDENTITY(GlobalTypes::CNetworkUtlVectorBase< uint8 >), 0xa80);
			PROPERTY(m_nVoxelFrameDataSize,int32_t, 0xa98);
			PROPERTY(m_nVoxelUpdate,int32_t, 0xa9c);
			NESTED_PROPERTY(m_flLastBounce,IDENTITY(entity2::GameTime_t), 0xaa0);
			NESTED_PROPERTY(m_fllastSimulationTime,IDENTITY(entity2::GameTime_t), 0xaa4);
			PROPERTY(m_bExplodeFromInferno,bool, 0x2d28);
			PROPERTY(m_bDidGroundScorch,bool, 0x2d29);
			S2_PAD(0x2300);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CSmokeGrenadeProjectile) == 0x2D30, "CSmokeGrenadeProjectile size should be 0x2D30");

#endif
	}
}
