// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CSoundEventEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundEventAABBEntity : public CS2::server::CSoundEventEntity {
		public:
			PROPERTY(m_vMins,GlobalTypes::Vector, 0x568);
			PROPERTY(m_vMaxs,GlobalTypes::Vector, 0x574);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CSoundEventAABBEntity) == 0x580, "CSoundEventAABBEntity size should be 0x580");

#endif
	}
}
