// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerRemove : public CS2::server::CBaseTrigger {
		public:
			NESTED_PROPERTY(m_OnRemove,IDENTITY(entity2::CEntityIOOutput), 0x8c8);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CTriggerRemove) == 0x8E0, "CTriggerRemove size should be 0x8E0");

#endif
	}
}
