// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerGameEvent : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_strStartTouchEventName,GlobalTypes::CUtlString*, 0x8c8);
			PROPERTY(m_strEndTouchEventName,GlobalTypes::CUtlString*, 0x8d0);
			PROPERTY(m_strTriggerID,GlobalTypes::CUtlString*, 0x8d8);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CTriggerGameEvent) == 0x8E0, "CTriggerGameEvent size should be 0x8E0");

#endif
	}
}
