// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CCSWeaponBaseGun.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CWeaponMag7 : public CS2::server::CCSWeaponBaseGun {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CWeaponMag7) == 0x1050, "CWeaponMag7 size should be 0x1050");

#endif
	}
}
