// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0xC8
			namespace CNmBlend2DNode_CDefinition /*: public CS2::animlib::CNmPoseNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_sourceNodeIndices = 0x10; // GlobalTypes::CUtlLeanVectorFixedGrowable  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_values = 0x28; // GlobalTypes::CUtlLeanVectorFixedGrowable<GlobalTypes::Vector2D>  | Schema_Atomic | Size: 0x58
				constexpr std::ptrdiff_t m_indices = 0x80; // GlobalTypes::CUtlLeanVectorFixedGrowable  | Schema_Atomic | Size: 0x28
				constexpr std::ptrdiff_t m_hullIndices = 0xa8; // GlobalTypes::CUtlLeanVectorFixedGrowable  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_nInputParameterNodeIdx0 = 0xc0; // int16_t m_nInputParameterNodeIdx0; |  0xc0 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_nInputParameterNodeIdx1 = 0xc2; // int16_t m_nInputParameterNodeIdx1; |  0xc2 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_bAllowLooping = 0xc4; // bool m_bAllowLooping; |  0xc4 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
