// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x60
			namespace CNmIDBasedClipSelectorNode_CDefinition /*: public CS2::animlib::CNmClipReferenceNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_optionNodeIndices = 0x10; // GlobalTypes::CUtlLeanVectorFixedGrowable  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_optionIDs = 0x28; // GlobalTypes::CUtlLeanVectorFixedGrowable<GlobalTypes::CGlobalSymbol>  | Schema_Atomic | Size: 0x30
				constexpr std::ptrdiff_t m_nParameterNodeIdx = 0x58; // int16_t m_nParameterNodeIdx; |  0x58 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_nFallbackNodeIdx = 0x5a; // int16_t m_nFallbackNodeIdx; |  0x5a | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_bIgnoreInvalidOptions = 0x5c; // bool m_bIgnoreInvalidOptions; |  0x5c | Schema_Builtin | Size: 0x1
			}
		}
	}
}
