// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x50
			namespace NmCompressionSettings_t /**/ {
				constexpr std::ptrdiff_t m_translationRangeX = 0x0; // animlib::NmCompressionSettings_t::QuantizationRange_t  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_translationRangeY = 0x8; // animlib::NmCompressionSettings_t::QuantizationRange_t  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_translationRangeZ = 0x10; // animlib::NmCompressionSettings_t::QuantizationRange_t  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_scaleRange = 0x18; // animlib::NmCompressionSettings_t::QuantizationRange_t  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_nTrackReadOffset = 0x20; // int32_t m_nTrackReadOffset; |  0x20 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_constantRotation = 0x30; // GlobalTypes::Quaternion  | Schema_Atomic | Size: 0x10
				constexpr std::ptrdiff_t m_bIsRotationStatic = 0x40; // bool m_bIsRotationStatic; |  0x40 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsTranslationStatic = 0x41; // bool m_bIsTranslationStatic; |  0x41 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsScaleStatic = 0x42; // bool m_bIsScaleStatic; |  0x42 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
