// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace pulse_system {
			// Class size: 0x10
			namespace TestComponent_t /**/ {
				constexpr std::ptrdiff_t m_ComponentData = 0x8; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
			}
		}
	}
}
