// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animgraphlib {
			// Class size: 0x1C
			namespace CCycleClipInstanceData /**/ {
				constexpr std::ptrdiff_t m_flCycle = 0x0; // GlobalTypes::CAnimNetVar  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flPrevCycle = 0xc; // GlobalTypes::CAnimNetVar  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
