// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animgraphlib {
			// Class size: 0x18
			namespace LookData /**/ {
				constexpr std::ptrdiff_t m_vLookTarget = 0x0; // GlobalTypes::CAnimNetVar<GlobalTypes::Vector>  | Schema_Atomic | Size: 0x14
			}
		}
	}
}
