// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animgraphlib {
			// Class size: 0xC
			namespace NetVarConfigIndex /**/ {
				constexpr std::ptrdiff_t m_index = 0x0; // GlobalTypes::CAnimNetVar  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
