// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animgraphlib {
			// Class size: 0xC
			namespace SlopeData /**/ {
				constexpr std::ptrdiff_t m_vSlopeNormal = 0x0; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
