// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace compositematerialslib {
		class GeneratedTextureHandle_t  {
		public:
			PROPERTY(m_strBitmapName,GlobalTypes::CUtlString*, 0x0);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::compositematerialslib::GeneratedTextureHandle_t) == 0x60, "GeneratedTextureHandle_t size should be 0x60");
	}
}
