// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace navlib {
		class NavHull_t  {
		public:
			PROPERTY(m_nHullIdx,int32_t, 0x0);
			S2_PAD(0x4);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::navlib::NavHull_t) == 0x4, "NavHull_t size should be 0x4");

#endif
	}
}
