// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/smartprops/CSmartPropOperation.hpp>
#include <SDK/smartprops/CSmartPropAttributeColorSelectionMode.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropOperation_MaterialTint : public CS2::smartprops::CSmartPropOperation {
		public:
			PROPERTY(m_Material,GlobalTypes::CSmartPropAttributeMaterialName, 0x50);
			NESTED_PROPERTY(m_SelectionMode,smartprops::CSmartPropAttributeColorSelectionMode, 0x90);
			PROPERTY(m_Color,GlobalTypes::CSmartPropAttributeColor, 0xd0);
			PROPERTY(m_Gradient,GlobalTypes::CColorGradient, 0x110);
			PROPERTY(m_ColorPosition,GlobalTypes::CSmartPropAttributeFloat, 0x128);
			S2_PAD(0x118);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropOperation_MaterialTint) == 0x168, "CSmartPropOperation_MaterialTint size should be 0x168");
	}
}
