// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/smartprops/CSmartPropTransformOperation.hpp>
#include <SDK/smartprops/CSmartPropAttributeCoordinateSpace.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropOperation_SetPosition : public CS2::smartprops::CSmartPropTransformOperation {
		public:
			PROPERTY(m_vPosition,GlobalTypes::CSmartPropAttributeVector, 0x50);
			NESTED_PROPERTY(m_CoordinateSpace,smartprops::CSmartPropAttributeCoordinateSpace, 0x90);
			S2_PAD(0x80);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropOperation_SetPosition) == 0xD0, "CSmartPropOperation_SetPosition size should be 0xD0");
	}
}
