// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropParameter  {
		public:
			PROPERTY(m_nElementID,int32_t, 0x8);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropParameter) == 0x10, "CSmartPropParameter size should be 0x10");
	}
}
