// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/smartprops/CSmartPropTransformOperation.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropOperation_ResetScale : public CS2::smartprops::CSmartPropTransformOperation {
		public:
			PROPERTY(m_bIgnoreObjectScale,GlobalTypes::CSmartPropAttributeBool, 0x50);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropOperation_ResetScale) == 0x90, "CSmartPropOperation_ResetScale size should be 0x90");
	}
}
