// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/smartprops/CSmartPropElement_Group.hpp>
#include <SDK/smartprops/CSmartPropAttributeGridPlacementMode.hpp>
#include <SDK/smartprops/CSmartPropAttributeGridOriginMode.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropElement_Layout2DGrid : public CS2::smartprops::CSmartPropElement_Group {
		public:
			PROPERTY(m_flWidth,GlobalTypes::CSmartPropAttributeFloat, 0xa0);
			PROPERTY(m_flLength,GlobalTypes::CSmartPropAttributeFloat, 0xe0);
			PROPERTY(m_bVerticalLength,GlobalTypes::CSmartPropAttributeBool, 0x120);
			NESTED_PROPERTY(m_GridArrangement,smartprops::CSmartPropAttributeGridPlacementMode, 0x160);
			NESTED_PROPERTY(m_GridOriginMode,smartprops::CSmartPropAttributeGridOriginMode, 0x1a0);
			PROPERTY(m_nCountW,GlobalTypes::CSmartPropAttributeInt, 0x1e0);
			PROPERTY(m_nCountL,GlobalTypes::CSmartPropAttributeInt, 0x220);
			PROPERTY(m_flSpacingWidth,GlobalTypes::CSmartPropAttributeFloat, 0x260);
			PROPERTY(m_flSpacingLength,GlobalTypes::CSmartPropAttributeFloat, 0x2a0);
			PROPERTY(m_bAlternateShift,GlobalTypes::CSmartPropAttributeBool, 0x2e0);
			PROPERTY(m_flAlternateShiftWidth,GlobalTypes::CSmartPropAttributeFloat, 0x320);
			PROPERTY(m_flAlternateShiftLength,GlobalTypes::CSmartPropAttributeFloat, 0x360);
			S2_PAD(0x300);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropElement_Layout2DGrid) == 0x3A0, "CSmartPropElement_Layout2DGrid size should be 0x3A0");
	}
}
