// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class BoneDemoCaptureSettings_t  {
		public:
			PROPERTY(m_boneName,GlobalTypes::CUtlString*, 0x0);
			PROPERTY(m_flErrorSplineRotationMax,float32, 0x8);
			PROPERTY(m_flErrorSplineTranslationMax,float32, 0xc);
			PROPERTY(m_flErrorSplineScaleMax,float32, 0x10);
			PROPERTY(m_flErrorQuantizationRotationMax,float32, 0x14);
			PROPERTY(m_flErrorQuantizationTranslationMax,float32, 0x18);
			PROPERTY(m_flErrorQuantizationScaleMax,float32, 0x1c);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animgraphlib::BoneDemoCaptureSettings_t) == 0x20, "BoneDemoCaptureSettings_t size should be 0x20");
	}
}
