// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimTagBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CAnimTagManagerUpdater  {
		public:
			NESTED_PROPERTY(m_tags,GlobalTypes::CUtlVector<GlobalTypes::CSmartPtr<animgraphlib::CAnimTagBase>>, 0x38);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::animgraphlib::CAnimTagManagerUpdater) == 0x78, "CAnimTagManagerUpdater size should be 0x78");
	}
}
