// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimUpdateSharedData.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CAnimGraphModelBinding  {
		public:
			PROPERTY(m_modelName,GlobalTypes::CUtlString*, 0x8);
			PROPERTY(m_pSharedData,GlobalTypes::CSmartPtr<animgraphlib::CAnimUpdateSharedData>, 0x10);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::animgraphlib::CAnimGraphModelBinding) == 0x28, "CAnimGraphModelBinding size should be 0x28");
	}
}
