// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimationGraphVisualizerPrimitiveBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CAnimationGraphVisualizerAxis : public CS2::animgraphlib::CAnimationGraphVisualizerPrimitiveBase {
		public:
			PROPERTY(m_xWsTransform,GlobalTypes::CTransform, 0x40);
			PROPERTY(m_flAxisSize,float32, 0x60);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::animgraphlib::CAnimationGraphVisualizerAxis) == 0x70, "CAnimationGraphVisualizerAxis size should be 0x70");
	}
}
