// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/modellib/AnimTagID.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CAnimTagBase  {
		public:
			PROPERTY(m_name,GlobalTypes::CGlobalSymbol, 0x18);
			PROPERTY(m_sComment,GlobalTypes::CUtlString*, 0x20);
			PROPERTY(m_group,GlobalTypes::CGlobalSymbol, 0x28);
			NESTED_PROPERTY(m_tagID,modellib::AnimTagID, 0x30);
			PROPERTY(m_bIsReferenced,bool, 0x48);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::animgraphlib::CAnimTagBase) == 0x50, "CAnimTagBase size should be 0x50");
	}
}
