// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CAnimReplayFrame  {
		public:
			NESTED_PROPERTY(m_inputDataBlocks,GlobalTypes::CUtlVector<GlobalTypes::CUtlBinaryBlock>, 0x10);
			PROPERTY(m_instanceData,GlobalTypes::CUtlBinaryBlock, 0x28);
			PROPERTY(m_startingLocalToWorldTransform,GlobalTypes::CTransform, 0x40);
			PROPERTY(m_localToWorldTransform,GlobalTypes::CTransform, 0x60);
			PROPERTY(m_timeStamp,float32, 0x80);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::animgraphlib::CAnimReplayFrame) == 0x90, "CAnimReplayFrame size should be 0x90");
	}
}
