// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimUpdateNodeBase.hpp>
#include <SDK/animgraphlib/BlendItem_t.hpp>
#include <SDK/animgraphlib/TagSpan_t.hpp>
#include <SDK/animgraphlib/CParamSpanUpdater.hpp>
#include <SDK/animgraphlib/CAnimInputDamping.hpp>
#include <SDK/animgraphlib/AnimValueSource.hpp>
#include <SDK/animgraphlib/CAnimParamHandle.hpp>
#include <SDK/animgraphlib/Blend2DMode.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CBlend2DUpdateNode : public CS2::animgraphlib::CAnimUpdateNodeBase {
		public:
			NESTED_PROPERTY(m_items,GlobalTypes::CUtlVector<animgraphlib::BlendItem_t>, 0x60);
			NESTED_PROPERTY(m_tags,GlobalTypes::CUtlVector<animgraphlib::TagSpan_t>, 0x78);
			NESTED_PROPERTY(m_paramSpans,animgraphlib::CParamSpanUpdater, 0x90);
			NESTED_PROPERTY(m_nodeItemIndices,GlobalTypes::CUtlVector< int32 >, 0xa8);
			NESTED_PROPERTY(m_damping,animgraphlib::CAnimInputDamping, 0xc0);
			PROPERTY(m_blendSourceX,animgraphlib::AnimValueSource, 0xd8);
			NESTED_PROPERTY(m_paramX,animgraphlib::CAnimParamHandle, 0xdc);
			PROPERTY(m_blendSourceY,animgraphlib::AnimValueSource, 0xe0);
			NESTED_PROPERTY(m_paramY,animgraphlib::CAnimParamHandle, 0xe4);
			PROPERTY(m_eBlendMode,animgraphlib::Blend2DMode, 0xe8);
			PROPERTY(m_playbackSpeed,float32, 0xec);
			PROPERTY(m_bLoop,bool, 0xf0);
			PROPERTY(m_bLockBlendOnReset,bool, 0xf1);
			PROPERTY(m_bLockWhenWaning,bool, 0xf2);
			PROPERTY(m_bAnimEventsAndTagsOnMostWeightedOnly,bool, 0xf3);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::animgraphlib::CBlend2DUpdateNode) == 0xF8, "CBlend2DUpdateNode size should be 0xF8");
	}
}
