// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CChoiceInstanceData  {
		public:
			PROPERTY(m_currentChoice,IDENTITY(GlobalTypes::CAnimNetVar< int32 >), 0x10);
			PROPERTY(m_previousChoice,int32_t, 0x1c);
			PROPERTY(m_flClipStartTime,IDENTITY(GlobalTypes::CAnimNetVar< float32 >), 0x20);
			PROPERTY(m_choicePreviousCycle,float32, 0x2c);
			S2_PAD(0x34);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animgraphlib::CChoiceInstanceData) == 0x34, "CChoiceInstanceData size should be 0x34");

#endif
	}
}
