// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CPathAnimMotorUpdaterBase.hpp>
#include <SDK/animgraphlib/CAnimParamHandle.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CDampedPathAnimMotorUpdater : public CS2::animgraphlib::CPathAnimMotorUpdaterBase {
		public:
			PROPERTY(m_flAnticipationTime,float32, 0x2c);
			PROPERTY(m_flMinSpeedScale,float32, 0x30);
			NESTED_PROPERTY(m_hAnticipationPosParam,animgraphlib::CAnimParamHandle, 0x34);
			NESTED_PROPERTY(m_hAnticipationHeadingParam,animgraphlib::CAnimParamHandle, 0x36);
			PROPERTY(m_flSpringConstant,float32, 0x38);
			PROPERTY(m_flMinSpringTension,float32, 0x3c);
			PROPERTY(m_flMaxSpringTension,float32, 0x40);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animgraphlib::CDampedPathAnimMotorUpdater) == 0x48, "CDampedPathAnimMotorUpdater size should be 0x48");
	}
}
