// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CFollowPathInstanceData  {
		public:
			PROPERTY(m_xLastPredictedTransformsDeltas,IDENTITY(GlobalTypes::CRelativeArray<GlobalTypes::CMotionTransform>), 0x0);
			PROPERTY(m_dampedTurnValue,float32, 0x8);
			PROPERTY(m_flTurnAmount,float32, 0xc);
			PROPERTY(m_flPredictionScale,IDENTITY(GlobalTypes::CAnimNetVar< float32 >), 0x10);
			PROPERTY(m_flLastPathTime,float32, 0x1c);
			S2_PAD(0x24);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animgraphlib::CFollowPathInstanceData) == 0x24, "CFollowPathInstanceData size should be 0x24");

#endif
	}
}
