// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CMotionMetricEvaluator.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CFutureFacingMetricEvaluator : public CS2::animgraphlib::CMotionMetricEvaluator {
		public:
			PROPERTY(m_flDistance,float32, 0x50);
			PROPERTY(m_flTime,float32, 0x54);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::animgraphlib::CFutureFacingMetricEvaluator) == 0x58, "CFutureFacingMetricEvaluator size should be 0x58");
	}
}
