// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimComponentUpdater.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CLODComponentUpdater : public CS2::animgraphlib::CAnimComponentUpdater {
		public:
			PROPERTY(m_nServerLOD,int32_t, 0x30);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::animgraphlib::CLODComponentUpdater) == 0x38, "CLODComponentUpdater size should be 0x38");
	}
}
