// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimTagBase.hpp>
#include <SDK/animgraphlib/MatterialAttributeTagType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CMaterialAttributeAnimTag : public CS2::animgraphlib::CAnimTagBase {
		public:
			PROPERTY(m_AttributeName,GlobalTypes::CUtlString*, 0x58);
			PROPERTY(m_AttributeType,animgraphlib::MatterialAttributeTagType_t, 0x60);
			PROPERTY(m_flValue,float32, 0x64);
			PROPERTY(m_Color,GlobalTypes::Color, 0x68);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animgraphlib::CMaterialAttributeAnimTag) == 0x70, "CMaterialAttributeAnimTag size should be 0x70");
	}
}
