// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CMotionGraphGroup.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CMotionDataSet  {
		public:
			NESTED_PROPERTY(m_groups,GlobalTypes::CUtlVector<animgraphlib::CMotionGraphGroup>, 0x0);
			PROPERTY(m_nDimensionCount,int32_t, 0x18);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animgraphlib::CMotionDataSet) == 0x20, "CMotionDataSet size should be 0x20");
	}
}
