// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CMoverInstanceData  {
		public:
			PROPERTY(m_flDampedValue,float32, 0x0);
			PROPERTY(m_vMovement,GlobalTypes::Vector, 0x4);
			PROPERTY(m_Rotation,GlobalTypes::CRotation, 0x1c);
			PROPERTY(m_TargetOrientation,GlobalTypes::CRotation, 0x20);
			S2_PAD(0x2C);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animgraphlib::CMoverInstanceData) == 0x2C, "CMoverInstanceData size should be 0x2C");

#endif
	}
}
