// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimMotorUpdaterBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CPathAnimMotorUpdaterBase : public CS2::animgraphlib::CAnimMotorUpdaterBase {
		public:
			PROPERTY(m_bLockToPath,bool, 0x20);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::animgraphlib::CPathAnimMotorUpdaterBase) == 0x28, "CPathAnimMotorUpdaterBase size should be 0x28");
	}
}
