// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CRootMotion  {
		public:
			PROPERTY(m_deltaTransform,GlobalTypes::CMotionTransform, 0x0);
			PROPERTY(m_vVelocityMS,GlobalTypes::Vector, 0x10);
			PROPERTY(m_vUpOverride,GlobalTypes::Vector, 0x1c);
			S2_PAD(0x28);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animgraphlib::CRootMotion) == 0x28, "CRootMotion size should be 0x28");

#endif
	}
}
