// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CWarpSectionAnimTagBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CWarpSectionAnimTag : public CS2::animgraphlib::CWarpSectionAnimTagBase {
		public:
			PROPERTY(m_bWarpPosition,bool, 0x50);
			PROPERTY(m_bWarpOrientation,bool, 0x51);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::animgraphlib::CWarpSectionAnimTag) == 0x58, "CWarpSectionAnimTag size should be 0x58");
	}
}
