// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerBase.hpp>
#include <SDK/soundsystem_voicecontainers/CSoundContainerReference.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerSwitch : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			NESTED_PROPERTY(m_soundsToPlay,GlobalTypes::CUtlVector<soundsystem_voicecontainers::CSoundContainerReference>, 0xa8);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerSwitch) == 0xC0, "CVoiceContainerSwitch size should be 0xC0");
	}
}
