// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerAsyncGenerator.hpp>
#include <SDK/soundsystem_voicecontainers/CTone.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerStaticAdditiveSynth : public CS2::soundsystem_voicecontainers::CVoiceContainerAsyncGenerator {
		public:
			NESTED_PROPERTY(m_tones,GlobalTypes::CUtlVector<soundsystem_voicecontainers::CTone>, 0xb8);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerStaticAdditiveSynth) == 0xE8, "CVoiceContainerStaticAdditiveSynth size should be 0xE8");
	}
}
