// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerStaticAdditiveSynth_CHarmonic.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerStaticAdditiveSynth_CTone  {
		public:
			NESTED_PROPERTY(m_harmonics,IDENTITY(GlobalTypes::CUtlVector<soundsystem_voicecontainers::CVoiceContainerStaticAdditiveSynth_CHarmonic>), 0x0);
			PROPERTY(m_curve,GlobalTypes::CPiecewiseCurve, 0x18);
			PROPERTY(m_bSyncInstances,bool, 0x58);
			S2_PAD(0x60);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerStaticAdditiveSynth_CTone) == 0x60, "CVoiceContainerStaticAdditiveSynth::CTone size should be 0x60");

#endif
	}
}
