// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmParameterizedBlendNode_CDefinition.hpp>
#include <SDK/animlib/CNmParameterizedBlendNode_Parameterization_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmBlend1DNode_CDefinition : public CS2::animlib::CNmParameterizedBlendNode_CDefinition {
		public:
			NESTED_PROPERTY(m_parameterization,IDENTITY(animlib::CNmParameterizedBlendNode_Parameterization_t), 0x30);
			S2_PAD(0x50);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmBlend1DNode_CDefinition) == 0x80, "CNmBlend1DNode::CDefinition size should be 0x80");

#endif
	}
}
