// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/NmCompressionSettings_t.hpp>
#include <SDK/animlib/NmFloatCurveCompressionSettings_t.hpp>
#include <SDK/animlib/CNmSyncTrack.hpp>
#include <SDK/animlib/CNmRootMotionData.hpp>
#include <SDK/animlib/ModelSpaceSamplingChainLink_t.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCNmSkeleton;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmClip  {
		public:
			PROPERTY(m_skeleton,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmSkeleton>, 0x0);
			PROPERTY(m_nNumFrames,uint32_t, 0x8);
			PROPERTY(m_flDuration,float32, 0xc);
			PROPERTY(m_compressedPoseData,GlobalTypes::CUtlBinaryBlock, 0x10);
			NESTED_PROPERTY(m_trackCompressionSettings,GlobalTypes::CUtlVector<animlib::NmCompressionSettings_t>, 0x20);
			NESTED_PROPERTY(m_compressedPoseOffsets,GlobalTypes::CUtlVector< uint32 >, 0x38);
			NESTED_PROPERTY(m_floatCurveIDs,GlobalTypes::CUtlVector<GlobalTypes::CGlobalSymbol>, 0x50);
			NESTED_PROPERTY(m_floatCurveDefs,GlobalTypes::CUtlVector<animlib::NmFloatCurveCompressionSettings_t>, 0x68);
			NESTED_PROPERTY(m_compressedFloatCurveData,GlobalTypes::CUtlVector< uint16 >, 0x80);
			NESTED_PROPERTY(m_compressedFloatCurveOffsets,GlobalTypes::CUtlVector< uint32 >, 0x98);
			PROPERTY(m_secondaryAnimations,GlobalTypes::CUtlVectorFixedGrowable<animlib::CNmClip*>, 0xd8);
			NESTED_PROPERTY(m_syncTrack,animlib::CNmSyncTrack, 0xf8);
			NESTED_PROPERTY(m_rootMotion,animlib::CNmRootMotionData, 0x1b0);
			PROPERTY(m_bIsAdditive,bool, 0x200);
			NESTED_PROPERTY(m_modelSpaceSamplingChain,GlobalTypes::CUtlVector<animlib::ModelSpaceSamplingChainLink_t>, 0x208);
			NESTED_PROPERTY(m_modelSpaceBoneSamplingIndices,GlobalTypes::CUtlVector< int32 >, 0x220);
			S2_PAD(0x240);
		};
		//static_assert(sizeof(CS2::animlib::CNmClip) == 0x240, "CNmClip size should be 0x240");
	}
}
