// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmIDValueNode_CDefinition.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmConstIDNode_CDefinition : public CS2::animlib::CNmIDValueNode_CDefinition {
		public:
			PROPERTY(m_value,GlobalTypes::CGlobalSymbol, 0x10);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmConstIDNode_CDefinition) == 0x18, "CNmConstIDNode::CDefinition size should be 0x18");

#endif
	}
}
