// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmFloatValueNode_CDefinition.hpp>
#include <SDK/animlib/CNmFloatAngleMathNode_Operation_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmFloatAngleMathNode_CDefinition : public CS2::animlib::CNmFloatValueNode_CDefinition {
		public:
			PROPERTY(m_nInputValueNodeIdx,int16_t, 0x10);
			PROPERTY(m_operation,IDENTITY(animlib::CNmFloatAngleMathNode_Operation_t), 0x12);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmFloatAngleMathNode_CDefinition) == 0x18, "CNmFloatAngleMathNode::CDefinition size should be 0x18");

#endif
	}
}
