// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmBoolValueNode_CDefinition.hpp>
#include <SDK/animlib/CNmFloatComparisonNode_Comparison_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmFloatComparisonNode_CDefinition : public CS2::animlib::CNmBoolValueNode_CDefinition {
		public:
			PROPERTY(m_nInputValueNodeIdx,int16_t, 0x10);
			PROPERTY(m_nComparandValueNodeIdx,int16_t, 0x12);
			PROPERTY(m_comparison,IDENTITY(animlib::CNmFloatComparisonNode_Comparison_t), 0x14);
			PROPERTY(m_flEpsilon,float32, 0x18);
			PROPERTY(m_flComparisonValue,float32, 0x1c);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmFloatComparisonNode_CDefinition) == 0x20, "CNmFloatComparisonNode::CDefinition size should be 0x20");

#endif
	}
}
