// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmFloatValueNode_CDefinition.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmFloatCurveNode_CDefinition : public CS2::animlib::CNmFloatValueNode_CDefinition {
		public:
			PROPERTY(m_nInputValueNodeIdx,int16_t, 0x10);
			PROPERTY(m_curve,GlobalTypes::CPiecewiseCurve, 0x18);
			S2_PAD(0x48);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmFloatCurveNode_CDefinition) == 0x58, "CNmFloatCurveNode::CDefinition size should be 0x58");

#endif
	}
}
