// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmPoseNode_CDefinition.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmIDBasedSelectorNode_CDefinition : public CS2::animlib::CNmPoseNode_CDefinition {
		public:
			// PROPERTY(m_optionNodeIndices,IDENTITY(GlobalTypes::CUtlLeanVectorFixedGrowable< int16, 5 >), 0x10);
			// PROPERTY(m_optionIDs,IDENTITY(GlobalTypes::CUtlLeanVectorFixedGrowable<GlobalTypes::CGlobalSymbol>), 0x28);
			PROPERTY(m_nParameterNodeIdx,int16_t, 0x58);
			PROPERTY(m_nFallbackNodeIdx,int16_t, 0x5a);
			PROPERTY(m_bIgnoreInvalidOptions,bool, 0x5c);
			S2_PAD(0x50);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmIDBasedSelectorNode_CDefinition) == 0x60, "CNmIDBasedSelectorNode::CDefinition size should be 0x60");

#endif
	}
}
