// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmPoseNode_CDefinition.hpp>
#include <SDK/animlib/CNmRootMotionData_SamplingMode_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmOrientationWarpNode_CDefinition : public CS2::animlib::CNmPoseNode_CDefinition {
		public:
			PROPERTY(m_nClipReferenceNodeIdx,int16_t, 0x10);
			PROPERTY(m_nTargetValueNodeIdx,int16_t, 0x12);
			PROPERTY(m_bIsOffsetNode,bool, 0x14);
			PROPERTY(m_bIsOffsetRelativeToCharacter,bool, 0x15);
			PROPERTY(m_bWarpTranslation,bool, 0x16);
			PROPERTY(m_samplingMode,IDENTITY(animlib::CNmRootMotionData_SamplingMode_t), 0x17);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmOrientationWarpNode_CDefinition) == 0x18, "CNmOrientationWarpNode::CDefinition size should be 0x18");

#endif
	}
}
