// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmPoseNode_CDefinition.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmParameterizedSelectorNode_CDefinition : public CS2::animlib::CNmPoseNode_CDefinition {
		public:
			// PROPERTY(m_optionNodeIndices,IDENTITY(GlobalTypes::CUtlLeanVectorFixedGrowable< int16, 8 >), 0x10);
			// PROPERTY(m_optionWeights,IDENTITY(GlobalTypes::CUtlLeanVectorFixedGrowable< uint8, 8 >), 0x28);
			PROPERTY(m_parameterNodeIdx,int16_t, 0x38);
			PROPERTY(m_bIgnoreInvalidOptions,bool, 0x3a);
			PROPERTY(m_bHasWeightsSet,bool, 0x3b);
			S2_PAD(0x30);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmParameterizedSelectorNode_CDefinition) == 0x40, "CNmParameterizedSelectorNode::CDefinition size should be 0x40");

#endif
	}
}
