// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/Event_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmSyncTrack  {
		public:
			PROPERTY(m_syncEvents,GlobalTypes::CUtlLeanVectorFixedGrowable<animlib::Event_t>, 0x0);
			PROPERTY(m_nStartEventOffset,int32_t, 0xa8);
			S2_PAD(0xB0);
		};
		//static_assert(sizeof(CS2::animlib::CNmSyncTrack) == 0xB0, "CNmSyncTrack size should be 0xB0");
	}
}
