// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/CNmPoseNode_CDefinition.hpp>
#include <SDK/animlib/CNmStateMachineNode_StateDefinition_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmStateMachineNode_CDefinition : public CS2::animlib::CNmPoseNode_CDefinition {
		public:
			// PROPERTY(m_stateDefinitions,IDENTITY(GlobalTypes::CUtlLeanVectorFixedGrowable<animlib::CNmStateMachineNode_StateDefinition_t>), 0x10);
			PROPERTY(m_nDefaultStateIndex,int16_t, 0x130);
			S2_PAD(0x128);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmStateMachineNode_CDefinition) == 0x138, "CNmStateMachineNode::CDefinition size should be 0x138");

#endif
	}
}
