// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animlib/QuantizationRange_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class NmFloatCurveCompressionSettings_t  {
		public:
			NESTED_PROPERTY(m_range,animlib::QuantizationRange_t, 0x0);
			PROPERTY(m_bIsStatic,bool, 0x8);
			S2_PAD(0xC);
		};
		//static_assert(sizeof(CS2::animlib::NmFloatCurveCompressionSettings_t) == 0xC, "NmFloatCurveCompressionSettings_t size should be 0xC");
	}
}
