// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x1068
			namespace C_Beam /*: public CS2::client::C_BaseModelEntity*/ {
				constexpr std::ptrdiff_t m_flFrameRate = 0xfa8; // float32 m_flFrameRate; |  0xfa8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flHDRColorScale = 0xfac; // float32 m_flHDRColorScale; |  0xfac | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFireTime = 0xfb0; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flDamage = 0xfb4; // float32 m_flDamage; |  0xfb4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nNumBeamEnts = 0xfb8; // uint8_t m_nNumBeamEnts; |  0xfb8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_queryHandleHalo = 0xfbc; // int32_t m_queryHandleHalo; |  0xfbc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hBaseMaterial = 0xfe0; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nHaloIndex = 0xfe8; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nBeamType = 0xff0; // client::BeamType_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_nBeamFlags = 0xff4; // uint32_t m_nBeamFlags; |  0xff4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hAttachEntity = 0xff8; // GlobalTypes::CHandle  | Schema_FixedArray | Size: 0x28
				constexpr std::ptrdiff_t m_nAttachIndex = 0x1020; // GlobalTypes::AttachmentHandle_t[10]  | Schema_FixedArray | Size: 0xa
				constexpr std::ptrdiff_t m_fWidth = 0x102c; // float32 m_fWidth; |  0x102c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fEndWidth = 0x1030; // float32 m_fEndWidth; |  0x1030 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fFadeLength = 0x1034; // float32 m_fFadeLength; |  0x1034 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fHaloScale = 0x1038; // float32 m_fHaloScale; |  0x1038 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fAmplitude = 0x103c; // float32 m_fAmplitude; |  0x103c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fStartFrame = 0x1040; // float32 m_fStartFrame; |  0x1040 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fSpeed = 0x1044; // float32 m_fSpeed; |  0x1044 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFrame = 0x1048; // float32 m_flFrame; |  0x1048 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nClipStyle = 0x104c; // client::BeamClipStyle_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bTurnedOff = 0x1050; // bool m_bTurnedOff; |  0x1050 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_vecEndPos = 0x1054; // GlobalTypes::VectorWS  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_hEndEntity = 0x1060; // GlobalTypes::CHandle<client::C_BaseEntity>  | Schema_Atomic | Size: 0x4
			}
		}
	}
}
