// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x608
			namespace C_EnvDetailController /*: public CS2::client::C_BaseEntity*/ {
				constexpr std::ptrdiff_t m_flFadeStartDist = 0x600; // float32 m_flFadeStartDist; |  0x600 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFadeEndDist = 0x604; // float32 m_flFadeEndDist; |  0x604 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
