// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x698
			namespace C_GradientFog /*: public CS2::client::C_BaseEntity*/ {
				constexpr std::ptrdiff_t m_hGradientFogTexture = 0x600; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_flFogStartDistance = 0x608; // float32 m_flFogStartDistance; |  0x608 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFogEndDistance = 0x60c; // float32 m_flFogEndDistance; |  0x60c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bHeightFogEnabled = 0x610; // bool m_bHeightFogEnabled; |  0x610 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flFogStartHeight = 0x614; // float32 m_flFogStartHeight; |  0x614 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFogEndHeight = 0x618; // float32 m_flFogEndHeight; |  0x618 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFarZ = 0x61c; // float32 m_flFarZ; |  0x61c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFogMaxOpacity = 0x620; // float32 m_flFogMaxOpacity; |  0x620 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFogFalloffExponent = 0x624; // float32 m_flFogFalloffExponent; |  0x624 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFogVerticalExponent = 0x628; // float32 m_flFogVerticalExponent; |  0x628 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fogColor = 0x62c; // GlobalTypes::Color  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_flFogStrength = 0x630; // float32 m_flFogStrength; |  0x630 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFadeTime = 0x634; // float32 m_flFadeTime; |  0x634 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bStartDisabled = 0x638; // bool m_bStartDisabled; |  0x638 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsEnabled = 0x639; // bool m_bIsEnabled; |  0x639 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bGradientFogNeedsTextures = 0x63a; // bool m_bGradientFogNeedsTextures; |  0x63a | Schema_Builtin | Size: 0x1
			}
		}
	}
}
