// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x690
			namespace CBaseAnimGraphController /*: public CS2::client::CSkeletonAnimationController*/ {
				constexpr std::ptrdiff_t m_nAnimationAlgorithm = 0x18; // client::AnimationAlgorithm_t  | Schema_DeclaredEnum | Size: 0x1
				constexpr std::ptrdiff_t m_nNextExternalGraphHandle = 0x1c; // client::ExternalAnimGraphHandle_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_vecSecondarySkeletonSlotIDs = 0x20; // GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CGlobalSymbol>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_vecSecondarySkeletons = 0x38; // GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CHandle<client::CBaseAnimGraph>>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_nSecondarySkeletonMasterCount = 0x50; // int32_t m_nSecondarySkeletonMasterCount; |  0x50 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flSoundSyncTime = 0x58; // float32 m_flSoundSyncTime; |  0x58 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nActiveIKChainMask = 0x5c; // uint32_t m_nActiveIKChainMask; |  0x5c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hSequence = 0xb0; // animationsystem::HSequence  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flSeqStartTime = 0xb4; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flSeqFixedCycle = 0xb8; // float32 m_flSeqFixedCycle; |  0xb8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nAnimLoopMode = 0xbc; // client::AnimLoopMode_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flPlaybackRate = 0xc0; // GlobalTypes::CNetworkedQuantizedFloat  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nNotifyState = 0xcc; // client::SequenceFinishNotifyState_t  | Schema_DeclaredEnum | Size: 0x1
				constexpr std::ptrdiff_t m_bNetworkedAnimationInputsChanged = 0xcd; // bool m_bNetworkedAnimationInputsChanged; |  0xcd | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bNetworkedSequenceChanged = 0xce; // bool m_bNetworkedSequenceChanged; |  0xce | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bLastUpdateSkipped = 0xcf; // bool m_bLastUpdateSkipped; |  0xcf | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bSequenceFinished = 0xd0; // bool m_bSequenceFinished; |  0xd0 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_nPrevAnimUpdateTick = 0xd4; // entity2::GameTick_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_hGraphDefinitionAG2 = 0x370; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmGraphDefinition>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_SerializePoseRecipeAG2Slots = 0x378; // GlobalTypes::C_UtlVectorEmbeddedNetworkVar<client::AnimGraph2SerializedPoseRecipeSlot_t>  | Schema_Atomic | Size: 0x68
				constexpr std::ptrdiff_t m_SerializePoseRecipeAG2Dynamic = 0x3e0; // GlobalTypes::C_NetworkUtlVectorBase  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_nSerializePoseRecipeAG2ActiveSlot = 0x3f8; // uint32_t m_nSerializePoseRecipeAG2ActiveSlot; |  0x3f8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nSerializePoseRecipeVersionAG2 = 0x3fc; // int32_t m_nSerializePoseRecipeVersionAG2; |  0x3fc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nServerGraphInstanceIteration = 0x400; // int32_t m_nServerGraphInstanceIteration; |  0x400 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nServerSerializationContextIteration = 0x404; // int32_t m_nServerSerializationContextIteration; |  0x404 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_primaryGraphId = 0x408; // resourcefile::ResourceId_t  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_vecExternalGraphIds = 0x410; // GlobalTypes::C_NetworkUtlVectorBase<resourcefile::ResourceId_t>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_vecExternalClipIds = 0x428; // GlobalTypes::C_NetworkUtlVectorBase<resourcefile::ResourceId_t>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_sAnimGraph2Identifier = 0x440; // GlobalTypes::CGlobalSymbol  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_pGraphInstanceAG2 = 0x448; // animlib::CNmGraphInstance**  | Schema_Ptr | Size: 0x8
				constexpr std::ptrdiff_t m_vecExternalGraphs = 0x660; // GlobalTypes::CUtlVector<client::ExternalAnimGraph_t>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_nPrevAnimationAlgorithm = 0x689; // client::AnimationAlgorithm_t  | Schema_DeclaredEnum | Size: 0x1
			}
		}
	}
}
