// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x1030
			namespace DebugDrawBoneTransforms_t /*: public CS2::client::DebugSnapshotBaseStructuredData_t*/ {
				constexpr std::ptrdiff_t vecBones = 0x10; // GlobalTypes::CUtlVectorFixedGrowable<GlobalTypes::CTransform>  | Schema_Atomic | Size: 0x1020
			}
		}
	}
}
