// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x20
			namespace GAME_HEADER /**/ {
				constexpr std::ptrdiff_t m_sComment = 0x0; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nSpawnGroupCount = 0x8; // int32_t m_nSpawnGroupCount; |  0x8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_sLandmark = 0x10; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_sRequiredAddons = 0x18; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
			}
		}
	}
}
