// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0xC
			namespace globalentity_t /**/ {
				constexpr std::ptrdiff_t name = 0x0; // GlobalTypes::CUtlSymbol  | Schema_Atomic | Size: 0x2
				constexpr std::ptrdiff_t levelName = 0x2; // GlobalTypes::CUtlSymbol  | Schema_Atomic | Size: 0x2
				constexpr std::ptrdiff_t state = 0x4; // client::GLOBALESTATE  | Schema_DeclaredEnum | Size: 0x1
				constexpr std::ptrdiff_t counter = 0x8; // int32_t counter; |  0x8 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
