// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x28
			namespace screenfade_t /**/ {
				constexpr std::ptrdiff_t Speed = 0x0; // float32 Speed; |  0x0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t End = 0x4; // float32 End; |  0x4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t Reset = 0x8; // float32 Reset; |  0x8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_Color = 0xc; // GlobalTypes::Color  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t Flags = 0x10; // int32_t Flags; |  0x10 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
